'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {loadCompatibility,saveCompatibility,reviewReadiness} from './actions';
import {MAX_BULK_LEARNERS,type Bindings} from './model';
type Config=Extract<Awaited<ReturnType<typeof loadCompatibility>>,{ok:true}>['data'];
type Review=Extract<Awaited<ReturnType<typeof reviewReadiness>>,{ok:true}>['data'];
const selectClass='min-h-11 w-full rounded-lg border border-[#E3E5E1] bg-white px-3 py-2 text-sm';
const panel='space-y-4 rounded-xl border border-[#E3E5E1] bg-white p-4 sm:p-6';
export function GenerationWorkspace({sectionId,templates}:{sectionId:string;templates:{id:string;name:string}[]}){
  const [templateId,setTemplate]=useState(''),[config,setConfig]=useState<Config|null>(null),[bindings,setBindings]=useState<Bindings>({periodBindings:{},subjectBindings:{}}),[confirmed,setConfirmed]=useState(false),[review,setReview]=useState<Review|null>(null),[gradeConfirmed,setGradeConfirmed]=useState(false),[formulaConfirmed,setFormulaConfirmed]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');const lock=useRef(false);
  async function run(label:string,fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(label);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{lock.current=false;setBusy('');}}
  function invalidate(){setReview(null);setGradeConfirmed(false);setFormulaConfirmed(false);setConfirmed(false);}
  async function configure(){await run('Loading compatibility…',async()=>{const r=await loadCompatibility({sectionId,templateId});if(!r.ok)throw new Error(r.error);setConfig(r.data);setBindings(r.data.profile?.bindings??{periodBindings:{},subjectBindings:{}});invalidate();});}
  async function save(){await run('Saving compatibility…',async()=>{if(!config)return;const r=await saveCompatibility({sectionId,templateId,mappingId:config.mappingId,mappingRevision:config.mappingRevision,sha:config.sha,expectedId:config.profile?.id??null,revision:config.profile?.revision??0,bindings,confirmed});if(!r.ok)throw new Error(r.error);setConfig({...config,profile:r.data});setBindings(r.data.bindings);setReview(null);setNotice('Compatibility saved. Review readiness to continue.');});}
  async function readiness(learnerId?:string){await run('Checking source and Grade Book…',async()=>{setReview(null);setGradeConfirmed(false);setFormulaConfirmed(false);const r=await reviewReadiness({sectionId,templateId,...(learnerId?{learnerId}:{})});if(!r.ok)throw new Error(r.error);setReview(r.data);});}
  async function download(all:boolean){await run(all?'Generating Section ZIP…':'Generating report card…',async()=>{if(!review)return;const r=await fetch(`/api/sections/${sectionId}/report-cards/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sectionId,templateId,profileId:review.profileId,profileRevision:review.profileRevision,digest:review.digest,learnerId:all?'all':review.learnerId,confirmed:gradeConfirmed,replaceFormulas:formulaConfirmed})});if(!r.ok){const result=await r.json();setReview(null);throw new Error(result.error??'Could not generate this download.');}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=decodeURIComponent(r.headers.get('X-Download-Filename')??'Report-Card.xlsx');document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Download ready. Generated files are not stored in TeacherCo.');});}
  const dirty=config?JSON.stringify(bindings)!==JSON.stringify(config.profile?.bindings):true;
  const canGenerate=!!review&&gradeConfirmed&&(!review.formulaTargets.length||formulaConfirmed)&&!busy;
  return <div className="space-y-5 pb-8">
    <div><h2 className="text-xl font-semibold text-[#1A4D2E]">Report Cards</h2><p className="mt-1 text-sm text-[#6B7280]">Choose a reviewed template, confirm compatibility, then review and download.</p></div>
    {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <p role="status" aria-live="polite" className="text-sm text-[#4F6F52]">{busy||notice}</p>
    <section className={panel}><h3 className="font-semibold">1. Template</h3><label className="block space-y-2 text-sm"><span>Active template with a reviewed mapping</span><select className={selectClass} value={templateId} disabled={!!busy} onChange={e=>{setTemplate(e.target.value);setConfig(null);invalidate();}}><option value="">Choose template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
      {!templates.length&&<p className="text-sm">No reviewed templates yet. <Link className="underline" href="/report-cards/templates">Manage templates and mappings</Link>.</p>}
      <Button variant="secondary" disabled={!templateId||!!busy} onClick={configure}>{config?'Reload compatibility':'Configure compatibility'}</Button></section>
    {config&&<section className={panel}><h3 className="font-semibold">2. Compatibility</h3><p className="text-sm text-[#6B7280]">Choose every match explicitly. Template labels never select Grade Book data automatically.</p>
      <div className="grid gap-4 sm:grid-cols-2">{config.definition.periods.map(p=><label key={p.key} className="space-y-2 text-sm"><span className="block">Template {p.label} → Section period</span><select className={selectClass} value={bindings.periodBindings[p.key]??''} disabled={!!busy} onChange={e=>{setBindings({...bindings,periodBindings:{...bindings.periodBindings,[p.key]:e.target.value}});invalidate();}}><option value="">Choose Section period</option>{config.periods.map(q=><option key={q.id} value={q.id}>{q.label} ({q.key})</option>)}</select></label>)}</div>
      <div className="grid gap-4 sm:grid-cols-2">{config.definition.subjects.map(s=><label key={s.key} className="space-y-2 text-sm"><span className="block">Template {s.label} → Section subject</span><select className={selectClass} value={bindings.subjectBindings[s.key]??''} disabled={!!busy} onChange={e=>{setBindings({...bindings,subjectBindings:{...bindings.subjectBindings,[s.key]:e.target.value}});invalidate();}}><option value="">Choose Section subject</option>{config.subjects.map(q=><option key={q.id} value={q.id}>{q.name}{q.code?` (${q.code})`:''} · {q.position}</option>)}</select></label>)}</div>
      <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={confirmed} disabled={!!busy} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these period and subject bindings.</label>
      <div className="flex flex-wrap gap-3"><Button disabled={!confirmed||!!busy} onClick={save}>Save compatibility</Button><Button variant="secondary" disabled={!config.profile||dirty||!!busy} onClick={()=>readiness()}>Review readiness</Button></div></section>}
    {review&&<section className={panel}><h3 className="font-semibold">3. Readiness</h3><p className="text-sm">Source verified · Mapping reviewed · {review.periodCount} periods bound · {review.subjectCount} subjects bound</p><p className="text-sm">{review.learners.length} active learners · {review.complete} complete · {review.missing} with missing values</p><p className="text-sm text-[#6B7280]">Missing values stay blank. Zero stays zero. LRN, final averages and remarks have no authoritative source in this batch and remain blank when mapped.</p>
      {review.missing>0&&<details><summary className="cursor-pointer text-sm font-medium">Missing-data warnings</summary><ul className="mt-3 max-h-64 space-y-2 overflow-y-auto text-sm">{review.learners.filter(l=>l.missingCount).map(l=><li key={l.id}><strong>{l.display_name}:</strong> {l.warnings.join('; ')}{l.missingCount>12?`; ${l.missingCount-12} more missing values`:''}</li>)}</ul></details>}
      <label className="block space-y-2 text-sm"><span>Preview learner</span><select className={selectClass} value={review.learnerId} disabled={!!busy||!review.learners.length} onChange={e=>readiness(e.target.value)}>{review.learners.map(l=><option key={l.id} value={l.id}>{l.display_name}</option>)}</select></label>
      <div role="region" aria-label="Learner output preview" tabIndex={0} className="max-h-96 overflow-auto rounded-lg border border-[#E3E5E1]"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-[#F5EFE6]"><tr><th className="p-3">Field</th><th className="p-3">Workbook location</th><th className="p-3">Value</th></tr></thead><tbody>{review.values.map(v=><tr key={v.id} className="border-t border-[#E3E5E1]"><td className="p-3">{v.label}</td><td className="break-all p-3">{v.location.sheet}!{v.location.address}</td><td className="break-words p-3">{v.value===null?<span className="text-amber-800">Missing</span>:v.value}</td></tr>)}</tbody></table></div>
      <p className="text-xs text-[#6B7280]">Ranges write to their top-left cell, including merged-cell masters. This preview does not change the workbook.</p>
      {!!review.formulaTargets.length&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><p>This mapped cell currently contains an Excel formula and will be replaced:</p><p className="break-all">{review.formulaTargets.join(', ')}</p><label className="mt-2 flex min-h-11 items-center gap-3"><input type="checkbox" checked={formulaConfirmed} disabled={!!busy} onChange={e=>setFormulaConfirmed(e.target.checked)}/>I confirm replacing these mapped formulas.</label></div>}
      <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={gradeConfirmed} disabled={!!busy} onChange={e=>setGradeConfirmed(e.target.checked)}/>I reviewed the Section Grade Book and accept the missing values shown.</label>
      <p className="text-sm text-[#6B7280]">One learner downloads an XLSX. All learners downloads one ZIP containing {review.learners.length} XLSX files. Initial limits: {MAX_BULK_LEARNERS} learners per ZIP; 3 MiB per source and download. No generated-file history is saved.</p>
      {review.learners.length>MAX_BULK_LEARNERS&&<p className="text-sm text-amber-800">This Section exceeds the bulk limit. Generate individual cards.</p>}
      <div className="flex flex-wrap gap-3"><Button disabled={!canGenerate||!review.learnerId} onClick={()=>download(false)}>Generate one</Button><Button variant="secondary" disabled={!canGenerate||!review.learners.length||review.learners.length>MAX_BULK_LEARNERS} onClick={()=>download(true)}>Generate all ({review.learners.length})</Button></div>
    </section>}
  </div>;
}
