'use client';
import {Spinner} from '@/components/ui/loading-state';
import {GradebookSetup} from '@/features/gradebook/setup';
import {loadGradebookSetup} from '@/features/gradebook/actions';
import { Select } from '@/components/ui/select';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {loadCompatibility,saveCompatibility,reviewReadiness} from './actions';
import {outputStatus,type Bindings} from './model';
import {receiveDownload} from './download-response';
import {suggestBindings} from '@/features/assisted-workflows/bindings';
type Config=Extract<Awaited<ReturnType<typeof loadCompatibility>>,{ok:true}>['data'];
type Review=Extract<Awaited<ReturnType<typeof reviewReadiness>>,{ok:true}>['data'];
const selectClass='min-h-11 w-full rounded-lg border border-[#E3E5E1] bg-white px-3 py-2 text-sm';
const panel='space-y-4 rounded-xl border border-[#E3E5E1] bg-white p-4 sm:p-6';
export function GenerationWorkspace({sectionId,templates,initial}:{sectionId:string;templates:{id:string;name:string}[];initial?:{templateId:string;config:Config;review:Review|null}}){
  const [templateId,setTemplate]=useState(initial?.templateId??''),[config,setConfig]=useState<Config|null>(initial?.config??null),[bindings,setBindings]=useState<Bindings>(initial?.config.profile?.bindings??(initial?suggestBindings(initial.config.definition,initial.config.periods,initial.config.subjects):{periodBindings:{},subjectBindings:{}})),[confirmed,setConfirmed]=useState(false),[review,setReview]=useState<Review|null>(initial?.review??null),[gradeConfirmed,setGradeConfirmed]=useState(false),[formulaConfirmed,setFormulaConfirmed]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');const lock=useRef(false);
  async function run(label:string,fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(label);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{lock.current=false;setBusy('');}}
  const [setup,setSetup]=useState<Extract<Awaited<ReturnType<typeof loadGradebookSetup>>,{ok:true}>['data']|null>(null);
  async function manageSubjects(){await run('Loading saved subjects...',async()=>{const result=await loadGradebookSetup({sectionId});if(!result.ok)throw new Error(result.error);setSetup(result.data);invalidate();});}
  const [lrns,setLrns]=useState<Record<string,string>>({}),[paste,setPaste]=useState(''),[batchStart,setBatchStart]=useState(0);
  useEffect(()=>{const clear=()=>{setLrns({});setPaste('');};window.addEventListener('pagehide',clear);return()=>window.removeEventListener('pagehide',clear);},[]);
  function invalidate(){setLrns({});setPaste('');setBatchStart(0);setReview(null);setGradeConfirmed(false);setFormulaConfirmed(false);setConfirmed(false);}
  async function configure(preserve=false){await run('Loading compatibility…',async()=>{const r=await loadCompatibility({sectionId,templateId});if(!r.ok)throw new Error(r.error);setConfig(r.data);setBindings(preserve?{periodBindings:{...suggestBindings(r.data.definition,r.data.periods,r.data.subjects).periodBindings,...bindings.periodBindings},subjectBindings:{...suggestBindings(r.data.definition,r.data.periods,r.data.subjects).subjectBindings,...bindings.subjectBindings}}:r.data.profile?.bindings??suggestBindings(r.data.definition,r.data.periods,r.data.subjects));invalidate();});}
  async function save(){await run('Saving compatibility…',async()=>{if(!config)return;const r=await saveCompatibility({sectionId,templateId,mappingId:config.mappingId,mappingRevision:config.mappingRevision,sha:config.sha,expectedId:config.profile?.id??null,revision:config.profile?.revision??0,bindings,confirmed});if(!r.ok)throw new Error(r.error);setConfig({...config,profile:r.data});setBindings(r.data.bindings);setReview(null);setNotice('Compatibility saved. Review readiness to continue.');});}
  async function readiness(learnerId?:string){await run('Checking source and Grade Book…',async()=>{setReview(null);setGradeConfirmed(false);setFormulaConfirmed(false);const r=await reviewReadiness({sectionId,templateId,...(learnerId?{learnerId}:{})});if(!r.ok)throw new Error(r.error);setReview(r.data);});}
  const batches=review?.batches??[],batch=batches.find(b=>b.start===batchStart)??batches[0],batchLearners=review?.learners.slice(batch?.start??0,(batch?.start??0)+(batch?.count??50))??[];
  const displayValues=review?.values.map(v=>v.id==='field:lrn'?{...v,value:lrns[review.learnerId]||null}:v)??[];
  const displayLearners=review?.learners.map(l=>{const supplied=review.lrnMapped&&/^\d{12}$/.test(lrns[l.id]??'');return {...l,missingCount:l.missingCount-(supplied?1:0),warnings:supplied?l.warnings.filter(w=>!/^LRN(?: missing|:)/.test(w)):l.warnings};})??[];
  const missingCount=displayLearners.filter(l=>l.missingCount>0).length;
  function pasteLrns(){const lines=paste.split(/\r?\n/).map(s=>s.trim());if(lines.length>batchLearners.length||lines.some(s=>s&&!/^\d{12}$/.test(s))){setError('Use one 12-digit LRN or a blank line per displayed learner.');return;}const next={...lrns};batchLearners.forEach((l,i)=>{next[l.id]=lines[i]??'';});setLrns(next);setPaste('');setGradeConfirmed(false);setError('');}
  async function download(all:boolean){await run(all?'Generating Section ZIP…':'Generating report card…',async()=>{if(!review)return;try{
    const selected=all?batchLearners:review.learners.filter(l=>l.id===review.learnerId),temporary=Object.fromEntries(selected.filter(l=>lrns[l.id]).map(l=>[l.id,lrns[l.id]]));
    if(Object.values(temporary).some(v=>!/^\d{12}$/.test(v)))throw new Error('Enter 12 digits for each temporary LRN, or leave it blank.');
    const r=await fetch(`/api/sections/${sectionId}/report-cards/generate`,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({sectionId,templateId,profileId:review.profileId,profileRevision:review.profileRevision,digest:review.digest,learnerId:all?'all':review.learnerId,...(all?{batchStart:batch?.start??0}:{}),...(Object.keys(temporary).length?{lrns:temporary}:{}),confirmed:gradeConfirmed,replaceFormulas:formulaConfirmed})});
    if(!r.ok){const result=await r.json();setReview(null);throw new Error(result.error??'Could not generate this download.');}
    const {blob,filename}=await receiveDownload(r,`/api/sections/${sectionId}/report-cards/cleanup`),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Download ready. Temporary LRN inputs were cleared. No permanent report-card history is saved.');
  }finally{setLrns({});setPaste('');setGradeConfirmed(false);}});}
  const dirty=config?JSON.stringify(bindings)!==JSON.stringify(config.profile?.bindings):true;
  const canGenerate=!!review&&gradeConfirmed&&(!review.formulaTargets.length||formulaConfirmed)&&!busy;
  return <div className="space-y-5 pb-8">
    <div><h2 className="text-xl font-semibold text-[#1A4D2E]">Report Cards</h2><p className="mt-1 text-sm text-[#6B7280]">Choose a template and review grades.</p></div>
    {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <p role="status" aria-live="polite" className="text-sm text-[#4F6F52]">{busy&&<Spinner className="mr-2"/>}{busy||notice}</p>
    <details className={panel} open={!review}><summary className="cursor-pointer font-semibold">1. Template{review?` · ${templates.find(t=>t.id===templateId)?.name??''}`:''}</summary><Select name={"Active template with a reviewed mapping"} label={"Active template with a reviewed mapping"} value={String(templateId)} disabled={!!busy} onChange={value => { setTemplate(value); setConfig(null); setSetup(null); invalidate(); }} emptyLabel={"Choose template"} options={templates.map(t => ({ value: String(t.id), label: t.name }))}/>
      {!templates.length&&<p className="text-sm">No reviewed templates yet. <Link className="tc-button tc-quiet " href="/report-cards/templates">Manage templates</Link>.</p>}
      <Button variant="secondary" disabled={!templateId||!!busy} onClick={()=>configure()}>{config?'Reload compatibility':'Configure compatibility'}</Button></details>
    {config&&<details className={panel} open={!review}><summary className="cursor-pointer font-semibold">2. Compatibility</summary><p className="text-sm text-[#6B7280]">Match the template to Section periods and subjects.</p>
      {!config.subjects.length&&<p className="text-sm text-[#606861]">This Section has no Grade Book subjects yet. Add your saved class subjects here to make them available for report cards.</p>}
      <Button variant="secondary" disabled={!!busy||!!setup} onClick={manageSubjects}>Add or manage Section subjects</Button>
      {setup&&<div className="rounded-xl border border-[#E3E5E1] p-3"><GradebookSetup book={setup.book} subjectOptions={setup.subjectOptions} onClose={()=>setSetup(null)} onSaved={()=>{setSetup(null);void configure(true);}}/></div>}
      <div className="grid gap-4 sm:grid-cols-2">{config.definition.periods.map(p=><Select name={`Template ${p.label} \u2192 Section period`} label={`Template ${p.label} \u2192 Section period`} key={p.key} value={String(bindings.periodBindings[p.key] ?? '')} disabled={!!busy} onChange={value => { setBindings({ ...bindings, periodBindings: { ...bindings.periodBindings, [p.key]: value } }); invalidate(); }} emptyLabel={"Choose Section period"} options={config.periods.map(q => ({ value: String(q.id), label: `${q.label} (${q.key})` }))}/>)}</div>
      <div className="grid gap-4 sm:grid-cols-2">{config.definition.subjects.map(s=><Select name={`Template ${s.label} \u2192 Section subject`} label={`Template ${s.label} \u2192 Section subject`} key={s.key} value={String(bindings.subjectBindings[s.key] ?? '')} disabled={!!busy||!!setup||!config.subjects.length} onChange={value => { setBindings({ ...bindings, subjectBindings: { ...bindings.subjectBindings, [s.key]: value } }); invalidate(); }} emptyLabel={"Choose Section subject"} options={config.subjects.map(q => ({ value: String(q.id), label: `${q.name}${q.code ? ` (${q.code})` : ''} \u00B7 ${q.position}` }))}/>)}</div>
      <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={confirmed} disabled={!!busy} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these period and subject bindings.</label>
      <div className="flex flex-wrap gap-3"><Button variant={review?'secondary':'primary'} disabled={!confirmed||!!busy||!!setup} onClick={save}>Save compatibility</Button><Button variant="secondary" disabled={!config.profile||dirty||!!busy||!!setup} onClick={()=>readiness()}>Review readiness</Button></div></details>}
    {review&&<section className={panel}><h3 className="font-semibold">3. Readiness</h3><p className="text-sm">Source verified · Mapping reviewed · {review.periodCount} periods bound · {review.subjectCount} subjects bound</p><p className="text-sm">{review.learners.length} active learners · {review.learners.length-missingCount} complete · {missingCount} with missing values</p><p className="text-sm text-[#6B7280]">Missing and unsupported values stay blank. Zero stays zero.</p>
      {missingCount>0&&<details><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Missing-data warnings</summary><ul className="mt-3 max-h-64 space-y-2 overflow-y-auto text-sm">{displayLearners.filter(l=>l.missingCount).map(l=><li key={l.id}><strong>{l.display_name}:</strong> {l.warnings.join('; ')}{l.missingCount>12?`; ${l.missingCount-12} more missing values`:''}</li>)}</ul></details>}
      {batches.length>1&&<Select name={"Download batch"} label={"Download batch"} value={String(batch?.start ?? 0)} disabled={!!busy} onChange={value => { setBatchStart(Number(value)); setGradeConfirmed(false); }} options={batches.map(b => ({ value: String(b.start), label: `${b.label} (${b.count} files)` }))}/>}
      {review.lrnMapped&&<fieldset className="space-y-3 rounded-lg border border-[#E3E5E1] p-3" disabled={!!busy}><legend className="px-1 text-sm font-semibold">Temporary LRN inputs</legend><p className="text-sm text-[#606861]">Optional · 12 digits · Never saved to learner records. Cleared after generation or leaving.</p>
        <details><summary className="min-h-11 cursor-pointer py-3 text-sm">Paste a column for this batch</summary><label className="block text-sm">LRNs in the displayed learner order<textarea autoComplete="off" spellCheck={false} className={`${selectClass} mt-2 min-h-24`} value={paste} onChange={e=>setPaste(e.target.value)} placeholder="One LRN per line; a blank line leaves that learner blank"/></label><Button variant="secondary" onClick={pasteLrns}>Apply pasted LRNs</Button></details>
        <div className="max-h-80 space-y-3 overflow-y-auto">{batchLearners.map((l,i)=><label key={l.id} className="block space-y-1 text-sm"><span>{(batch?.start??0)+i+1}. {l.display_name} — temporary LRN</span><input autoComplete="off" spellCheck={false} inputMode="numeric" maxLength={12} className={selectClass} value={lrns[l.id]??''} onChange={e=>{setLrns({...lrns,[l.id]:e.target.value});setGradeConfirmed(false);}}/></label>)}</div>
        {!batchLearners.some(l=>l.id===review.learnerId)&&<label className="block space-y-1 text-sm"><span>Preview learner — temporary LRN</span><input autoComplete="off" spellCheck={false} inputMode="numeric" maxLength={12} className={selectClass} value={lrns[review.learnerId]??''} onChange={e=>{setLrns({...lrns,[review.learnerId]:e.target.value});setGradeConfirmed(false);}}/></label>}
        <Button variant="ghost" onClick={()=>{setLrns({});setPaste('');setGradeConfirmed(false);}}>Clear temporary LRNs</Button>
      </fieldset>}
      <Select name={"Preview learner"} label={"Preview learner"} value={String(review.learnerId)} disabled={!!busy || !review.learners.length} onChange={value => readiness(value)} options={review.learners.map(l => ({ value: String(l.id), label: l.display_name }))}/>
      <div role="region" aria-label="Learner output preview" tabIndex={0} className="max-h-96 overflow-auto rounded-lg border border-[#E3E5E1]"><table className="w-full min-w-[520px] text-left text-sm"><thead className="bg-[#F5EFE6]"><tr><th className="p-3">Field</th><th className="p-3">Workbook location</th><th className="p-3">Value</th><th className="p-3">Status</th></tr></thead><tbody>{displayValues.map(v=><tr key={v.id} className="border-t border-[#E3E5E1]"><td className="p-3">{v.label}</td><td className="break-all p-3">{v.location.sheet}!{v.location.address}</td><td className="break-words p-3">{v.value===null?<span className="text-amber-800">Missing</span>:v.value}</td><td className="p-3">{outputStatus(v)}</td></tr>)}</tbody></table></div>
      <p className="text-xs text-[#6B7280]">Read-only preview. Ranges write to their top-left cell.</p>
      {!!review.formulaTargets.length&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm"><p>This mapped cell currently contains an Excel formula and will be replaced:</p><p className="break-all">{review.formulaTargets.join(', ')}</p><label className="mt-2 flex min-h-11 items-center gap-3"><input type="checkbox" checked={formulaConfirmed} disabled={!!busy} onChange={e=>setFormulaConfirmed(e.target.checked)}/>I confirm replacing these mapped formulas.</label></div>}
      <label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={gradeConfirmed} disabled={!!busy} onChange={e=>setGradeConfirmed(e.target.checked)}/>I reviewed the Section Grade Book and accept the missing values shown.</label>
      <p className="text-sm text-[#6B7280]">XLSX per learner · ZIP: {batchLearners.length} of {review.learners.length} learners · Temporary private downloads.</p>
      {batches.length>1&&<p className="text-sm text-amber-800">Download every batch to include all learners.</p>}
      <div className="flex flex-wrap gap-3"><Button variant="secondary" disabled={!canGenerate||!review.learnerId} onClick={()=>download(false)}>Generate one</Button><Button disabled={!canGenerate||!batchLearners.length} onClick={()=>download(true)}>{batches.length>1?`Generate batch (${batchLearners.length})`:`Generate all (${review.learners.length})`}</Button></div>
    </section>}
  </div>;
}
