'use client';
import { useEffect,useRef,useState,useTransition } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Select } from '@/components/ui/select';
import { FileUpload } from '@/components/ui/file-upload';
import { columnLetter,fileValidation } from '@/features/report-card-templates/model';
import type { GradebookData } from '@/features/gradebook/data';
import { analyzeGradeFile,applyGradeFile } from './grade-actions';
import { discoverClassSync,applyClassSync } from './sync-actions';
import type { GradeFormat } from './grades';
type Analysis=Extract<Awaited<ReturnType<typeof analyzeGradeFile>>,{ok:true}>['data'];
type Sync=Extract<Awaited<ReturnType<typeof discoverClassSync>>,{ok:true}>['data'];
type Item={id:string;file:File;analysis?:Analysis;error?:string;done?:boolean;use:number[];skip:number[];review?:boolean};
const input='min-h-11 w-full rounded-lg border border-[#E3E5E1] bg-white px-3';
export function GradeInbox({book}:{book:GradebookData}){
  const [items,setItems]=useState<Item[]>([]),[sync,setSync]=useState<Sync|null>(null),[decisions,setDecisions]=useState<Record<string,boolean>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(''),[pending,start]=useTransition(),lock=useRef(false),router=useRouter();
  const active=book.section.status==='active',subjects=book.subjects.filter(s=>s.status==='active'),periods=book.periods.filter(p=>p.status==='active'),learners=book.learners.filter(l=>l.status==='active');
  useEffect(()=>{let current=true;if(active)void discoverClassSync(book.section.id).then(r=>{if(current){if(r.ok)setSync(r.data);else setError(r.error);}});return()=>{current=false;};},[active,book.section.id]);
  function run(label:string,work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(label);setError('');start(async()=>{try{await work();}catch{setError('Connection interrupted. Refresh the preview before retrying.');}finally{lock.current=false;setBusy('');}});}
  function patch(id:string,update:Partial<Item>){setItems(old=>old.map(i=>i.id===id?{...i,...update}:i));}
  function payload(item:Item,selection= item.analysis?.selection){const form=new FormData();form.set('file',item.file);form.set('selection',JSON.stringify(selection??{sectionId:book.section.id,subjectId:null,periodId:null,format:null,resolutions:{}}));return form;}
  async function analyze(item:Item,selection=item.analysis?.selection){const r=await analyzeGradeFile(payload(item,selection));patch(item.id,r.ok?{analysis:r.data,error:undefined,use:[],skip:[]}:{error:r.error});}
  function destinations(item:Item){const p=item.analysis?.selection;return !!p?.subjectId&&!!p.format&&(p.format.gradeColumns??[p.format.gradeColumn]).every(c=>p.periodBindings?.[c]||(c===p.format!.gradeColumn&&p.periodId));}
  function issues(item:Item){return item.analysis?.rows.filter(r=>!['ready','unchanged','missing'].includes(r.kind))??[];}
  function ready(item:Item){return !item.done&&destinations(item)&&!!item.analysis&&item.analysis.source!=='review'&&(!item.analysis.sectionMismatch||item.analysis.selection.sectionConfirmed)&&item.analysis.rows.some(r=>!item.skip.includes(r.row)&&(r.kind==='ready'||r.kind==='conflict'&&item.use.includes(r.row)))&&item.analysis.rows.every(r=>['ready','unchanged','missing'].includes(r.kind)||item.skip.includes(r.row)||r.kind==='conflict'&&item.use.includes(r.row));}
  async function importFile(item:Item){if(!item.analysis)return false;const form=payload(item);form.set('approval',JSON.stringify({digest:item.analysis.digest,confirmed:true,useIncoming:item.use,skip:item.skip,remember:true}));const r=await applyGradeFile(form);if(r.ok){patch(item.id,{done:true,error:r.data.remembered?undefined:'Grades imported; format could not be remembered.'});return true;}patch(item.id,{error:r.error});return false;}
  async function importReady(){let count=0;for(const item of items.filter(ready)){if(!await importFile(item))break;count++;}setNotice(`${count} files imported.`);router.refresh();}
  function upload(files:File[]){if(!files.length)return;if(files.length>10||files.some(f=>f.size>8*1024*1024||fileValidation(f.name,f.size,f.type))){setError('Choose up to 10 .xlsx files, each up to 8 MiB.');return;}const next=files.map(file=>({id:crypto.randomUUID(),file,use:[],skip:[]}));setItems(next);run('Analyzing files…',async()=>{for(const item of next)await analyze(item);});}
  async function syncAll(){if(!sync)return;let count=0;for(const proposal of sync.proposals){const incoming=proposal.preview.rows.filter(r=>r.status==='change'&&decisions[`${proposal.name}:${r.learnerId}`]).map(r=>r.learnerId);const r=await applyClassSync({selection:proposal.selection,digest:proposal.preview.digest,useIncoming:incoming,confirmed:true});if(!r.ok){setError(`${proposal.name}: ${r.error} ${count} grades already synced.`);break;}count+=r.count;}const fresh=await discoverClassSync(book.section.id);if(fresh.ok)setSync(fresh.data);setDecisions({});setNotice(`${count} grades synced.`);router.refresh();}
  const conflicts=sync?.proposals.flatMap(p=>p.preview.rows.filter(r=>r.status==='change').map(r=>({proposal:p,row:r,key:`${p.name}:${r.learnerId}`})))??[];
  return <div className="space-y-5"><header className="flex flex-wrap justify-between gap-3"><h2>Grade Inbox</h2><Link className="tc-button tc-quiet" href={`/sections/${book.section.id}/grades`}>Edit Grade Book</Link></header>
    {error&&<p role="alert" className="text-red-800">{error}</p>}{(busy||notice)&&<p role="status">{busy||notice}</p>}
    <section className="tc-group divide-y divide-[#E3E5E1]">{subjects.map(s=>{const missing=periods.reduce((n,p)=>n+learners.filter(l=>!book.entries.some(e=>e.section_subject_id===s.id&&e.period_id===p.id&&e.learner_id===l.id&&e.grade!=null)).length,0);return <div key={s.id} className="flex justify-between gap-3 p-4"><span>{s.name}</span><span className="text-sm">{!periods.length||!learners.length?'Needs setup':missing?`${missing} missing`:'✓ Ready'}</span></div>;})}{!subjects.length&&<p className="p-4">Add subjects and periods in Grade Book.</p>}</section>
    {active&&<>
      <section className="tc-group p-4 space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3>TeacherCo classes</h3><Button variant="ghost" disabled={pending} onClick={()=>run('Checking linked classes…',async()=>{const r=await discoverClassSync(book.section.id);if(r.ok){setSync(r.data);setDecisions({});}else setError(r.error);})}>Check updates</Button></div>{!sync?<p>Checking linked classes…</p>:<><p>{sync.proposals.length} subject periods have updates</p>{sync.issues.length>0&&<details><summary className="cursor-pointer">{sync.issues.length} things need attention</summary>{sync.issues.map((s,i)=><p className="py-2 text-sm" key={i}>{s}</p>)}<Link className="tc-button tc-quiet" href={`/sections/${book.section.id}/grades`}>Review sources</Link></details>}{conflicts.map(({proposal,row,key})=><div className="border-t border-[#E3E5E1] py-3" key={key}><p>{row.name} · {proposal.name}</p><p className="text-sm">Current: {row.current?.grade} · Incoming: {row.incoming}</p><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={pending} aria-pressed={decisions[key]===true} onClick={()=>setDecisions({...decisions,[key]:true})}>Use {row.incoming}</Button><Button variant="ghost" disabled={pending} aria-pressed={decisions[key]===false} onClick={()=>setDecisions({...decisions,[key]:false})}>Keep {row.current?.grade}</Button></div></div>)}<Button variant={items.length?'secondary':'primary'} disabled={pending||!sync.proposals.length||conflicts.some(c=>!(c.key in decisions))} onClick={()=>run('Syncing changes…',syncAll)}>Sync {new Set(sync.proposals.map(p=>p.selection.subjectId)).size} subjects</Button></>}</section>
      <section className="tc-group p-4 space-y-3"><h3>Import grades</h3><FileUpload label="Upload grade files" multiple disabled={pending||!subjects.length||!periods.length} onFiles={upload}/><p className="text-xs">Up to 10 files · 8 MiB each</p></section>
      {items.length>0&&<p>{items.filter(i=>i.analysis).length} files analyzed · {items.filter(ready).length} ready</p>}
      {items.length>0&&<Button disabled={pending||!items.some(ready)} onClick={()=>run('Importing reviewed files…',importReady)}>Import reviewed files ({items.filter(ready).length})</Button>}
      {items.map(item=><section key={item.id} className="tc-group p-4 space-y-4"><h3 className="break-words">{item.file.name}{item.done?' · Imported':''}</h3>{item.error&&<div><p role="alert" className="text-red-800">{item.error}</p>{!item.done&&<Button variant="ghost" disabled={pending} onClick={()=>run('Analyzing file…',()=>analyze(item))}>Retry analysis</Button>}</div>}{!item.analysis&&!item.error?<p>Waiting for analysis…</p>:!item.done&&item.analysis&&<>
        <details open={!destinations(item)||item.analysis.source==='review'}><summary className="cursor-pointer text-sm">{subjects.find(s=>s.id===item.analysis!.selection.subjectId)?.name??'Choose subject'} · {(item.analysis.selection.format?.gradeColumns??[item.analysis.selection.format?.gradeColumn]).map(c=>periods.find(p=>p.id===(item.analysis!.selection.periodBindings?.[c!]??item.analysis!.selection.periodId))?.label??'Choose period').join(', ')}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><Select name={`subject-${item.id}`} label="Subject" value={item.analysis.selection.subjectId??''} emptyLabel="Choose subject" disabled={pending} options={subjects.map(s=>({value:s.id,label:s.name}))} onChange={value=>run('Checking grades…',()=>analyze(item,{...item.analysis!.selection,subjectId:value}))}/>{(item.analysis.selection.format?.gradeColumns??[item.analysis.selection.format?.gradeColumn??2]).map(column=><Select key={column} name={`period-${item.id}-${column}`} label={(item.analysis!.selection.format?.gradeColumns?.length??1)>1?`${columnLetter(column)} period`:'Period'} value={item.analysis!.selection.periodBindings?.[column]??item.analysis!.selection.periodId??''} emptyLabel="Choose period" disabled={pending} options={periods.map(p=>({value:p.id,label:p.label}))} onChange={value=>run('Checking grades…',()=>analyze(item,{...item.analysis!.selection,periodId:(item.analysis!.selection.format?.gradeColumns?.length??1)>1?null:value,periodBindings:{...item.analysis!.selection.periodBindings,[column]:value}}))}/>)}</div></details>
        <details open={!item.analysis.selection.format}><summary className="cursor-pointer">{item.analysis.source==='remembered'?'Recognized format':'File layout'}</summary><FormatEditor key={JSON.stringify(item.analysis.selection.format)} initial={item.analysis.selection.format} sheets={item.analysis.sheets} disabled={pending} onApply={format=>run('Checking layout…',()=>analyze(item,{...item.analysis!.selection,format,periodBindings:format.sheet===item.analysis!.selection.format?.sheet&&format.headerRow===item.analysis!.selection.format?.headerRow?item.analysis!.selection.periodBindings:{},periodId:null}))}/></details>
        {item.analysis.source==='review'&&destinations(item)&&<Button variant="secondary" disabled={pending} onClick={()=>run('Checking selections...',()=>analyze(item))}>Use these selections</Button>}
        {item.analysis.sectionMismatch&&!item.analysis.selection.sectionConfirmed&&<div className="space-y-2"><p>File Section: {item.analysis.sectionMismatch}</p><Button variant="secondary" disabled={pending} onClick={()=>run('Checking Section…',()=>analyze(item,{...item.analysis!.selection,sectionConfirmed:true}))}>Use {book.section.name}</Button></div>}
        <p>{new Set(item.analysis.rows.map(r=>r.sourceRow??r.row)).size} learners · {item.analysis.rows.filter(r=>r.kind==='ready'||r.kind==='unchanged').length} grades ready{item.analysis.rows.some(r=>r.kind==='missing')?' · Blank cells skipped':''}</p>
        {issues(item).length>0&&<Button variant="secondary" disabled={pending} aria-expanded={!!item.review} onClick={()=>patch(item.id,{review:!item.review})}>Review {issues(item).filter(r=>!item.skip.includes(r.row)&&!item.use.includes(r.row)).length} issues</Button>}
        {item.review&&issues(item).map(r=><div className="border-t border-[#E3E5E1] py-3 space-y-2" key={r.row}><p>{r.name||`Row ${r.sourceRow??r.row}`}{(item.analysis!.selection.format?.gradeColumns?.length??1)>1?` · ${r.periodLabel}`:''} · {r.kind==='conflict'?`Current: ${r.current?.grade} · Incoming: ${r.incoming}`:r.kind==='match'?'Choose learner':r.kind==='duplicate'?'Duplicate learner':'Invalid or missing grade'}</p>{r.kind==='match'&&<Select name={`learner-${item.id}-${r.row}`} label="Match learner" value="" emptyLabel="Choose learner" disabled={pending} options={learners.map(l=>({value:l.id,label:`${l.display_name}${r.candidates.includes(l.id)?' · Possible match':''}`}))} onChange={value=>run('Checking match…',()=>analyze(item,{...item.analysis!.selection,resolutions:{...item.analysis!.selection.resolutions,[r.sourceRow??r.row]:value}}))}/>}<div className="flex flex-wrap gap-2">{r.kind==='conflict'&&<Button variant="secondary" aria-pressed={item.use.includes(r.row)} onClick={()=>patch(item.id,{use:[...item.use,r.row],skip:item.skip.filter(n=>n!==r.row)})}>Use {r.incoming}</Button>}<Button variant="ghost" aria-pressed={item.skip.includes(r.row)} onClick={()=>patch(item.id,{skip:[...item.skip,r.row],use:item.use.filter(n=>n!==r.row)})}>{r.kind==='conflict'?`Keep ${r.current?.grade}`:'Skip row'}</Button></div></div>)}
        <details><summary className="cursor-pointer text-sm">More</summary><Button variant="ghost" disabled={pending} onClick={()=>run('Refreshing preview…',()=>analyze(item))}>Refresh preview</Button></details>
        <Button variant="secondary" disabled={pending||!ready(item)} onClick={()=>run('Importing grades…',async()=>{await importFile(item);router.refresh();})}>Import this file</Button>
      </>}</section>)}
    </>}
    <Link className="tc-button tc-secondary" href={`/sections/${book.section.id}/report-cards`}>Report Cards</Link>
  </div>;
}
function FormatEditor({initial,sheets,disabled,onApply}:{initial:GradeFormat|null;sheets:Analysis['sheets'];disabled:boolean;onApply:(format:GradeFormat)=>void}){
  const [format,setFormat]=useState<GradeFormat>(initial??{sheet:0,headerRow:1,nameColumn:1,gradeColumn:2,uuidColumn:null,startRow:2,endRow:Math.min(500,sheets[0]?.rows??2)});
  const [columns,setColumns]=useState((format.gradeColumns??[format.gradeColumn]).join(', '));
  const selected=columns.split(',').map(c=>Number(c.trim())),valid=selected.length<=8&&selected.every(c=>Number.isInteger(c)&&c>0&&c<=128)&&new Set(selected).size===selected.length&&!selected.includes(format.nameColumn);
  return <fieldset disabled={disabled} className="mt-3 grid gap-3 sm:grid-cols-2"><Select name="layout-sheet" label="Worksheet" value={String(format.sheet)} options={sheets.map(s=>({value:String(s.index),label:s.name}))} onChange={v=>setFormat({...format,sheet:Number(v),endRow:Math.min(500,sheets[Number(v)].rows)})}/>{(['headerRow','nameColumn','startRow','endRow'] as const).map(key=><label key={key} className="text-sm">{{headerRow:'Header row',nameColumn:'Name column number',gradeColumn:'Grade column number',startRow:'First learner row',endRow:'Last learner row'}[key]}<input type="number" min={1} max={2000} className={input} value={format[key]} onChange={e=>setFormat({...format,[key]:Number(e.target.value)})}/></label>)}<label className="text-sm">Grade column numbers<input className={input} value={columns} onChange={e=>setColumns(e.target.value)}/></label><Button variant="secondary" disabled={!valid} onClick={()=>onApply({...format,gradeColumn:selected[0],gradeColumns:selected,periodHints:[]})}>Use layout</Button></fieldset>;
}
