import Link from 'next/link';
import { listTemplates } from '@/features/report-card-templates/data';
import { fileSize } from '@/features/report-card-templates/model';
export const metadata={title:'Report card templates'};
export default async function TemplatesPage(){
  const templates=await listTemplates();
  return <div className="min-w-0 space-y-6"><Link href="/settings#academic-tools" className="inline-flex min-h-11 items-center text-sm text-[#4F6F52]">Back to Settings</Link><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">Report card templates</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#606861]">Keep your blank Excel layouts here and inspect their worksheets. Templates belong to your account.</p></div><Link href="/report-cards/templates/new" className="tc-button tc-primary">Upload template</Link></div>
  {!templates.length?<div className="tc-group p-6"><h2 className="font-semibold">Your templates will appear here</h2><p className="mt-2 text-sm text-[#606861]">Upload a blank .xlsx report card to get started. The original workbook is preserved.</p></div>:(['active','archived'] as const).map(status=>{const rows=templates.filter(t=>t.status===status);return rows.length>0&&<section key={status} className="space-y-3"><h2 className="font-semibold">{status==='active'?'Active templates':'Archived templates'}</h2><div className="tc-group divide-y divide-[#E3E5E1]">{rows.map(t=><Link key={t.id} href={`/report-cards/templates/${t.id}`} className="block min-h-11 p-4 hover:bg-[#F5EFE6]"><p className="break-words font-medium">{t.name}</p><p className="mt-1 break-words text-xs text-[#606861]">{t.original_filename} · {t.sheet_count} worksheets · {fileSize(t.file_size_bytes)}</p><p className="mt-1 text-xs text-[#606861]">Uploaded <time dateTime={t.created_at}>{new Intl.DateTimeFormat('en-PH',{dateStyle:'medium',timeZone:'Asia/Manila'}).format(new Date(t.created_at))}</time></p></Link>)}</div></section>;})}</div>;
}
