// @vitest-environment node
import { randomUUID } from 'node:crypto';
import { beforeAll,afterAll,it,expect } from 'vitest';
import type { PGlite } from '@electric-sql/pglite';
import { database } from './helpers/database';
let db:PGlite;
beforeAll(async()=>{db=await database(24);},30000);
afterAll(async()=>{await db?.close();});
async function fixture(){const teacher=randomUUID(),section=randomUUID(),subject=randomUUID(),period=randomUUID(),learner=randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'assisted@example.invalid',now())",[teacher]);await db.query("update profiles set access_status='active' where id=$1",[teacher]);await db.query("insert into sections(id,teacher_id,name,grade_level,school_year) values($1,$2,'A','Grade 1','2026-2027')",[section,teacher]);await db.query("insert into learners(id,teacher_id,display_name) values($1,$2,'Synthetic')",[learner,teacher]);await db.query('insert into section_enrollments(teacher_id,section_id,learner_id) values($1,$2,$3)',[teacher,section,learner]);await db.query("insert into section_subjects(id,teacher_id,section_id,name,position) values($1,$2,$3,'Science',1)",[subject,teacher,section]);await db.query("insert into section_grade_periods(id,teacher_id,section_id,key,label,position) values($1,$2,$3,'period_1','Term 1',1)",[period,teacher,section]);return {teacher,section,subject,period,learner};}
async function actor(id:string,work:()=>Promise<void>){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');try{await work();}finally{await db.exec('reset role');}}
const format={sheet:0,headerRow:1,nameColumn:1,gradeColumn:2,uuidColumn:null,startRow:2,endRow:30};
it('saves numeric multi-column formats without accepting protection or learner internals',async()=>{const a=await fixture();await actor(a.teacher,async()=>{const definition={...format,gradeColumns:[2,3,4,5],periodHints:[{column:2,code:1},{column:3,code:2}]};await db.query('insert into grade_import_formats(teacher_id,fingerprint,definition) values($1,$2,$3)',[a.teacher,'d'.repeat(64),JSON.stringify(definition)]);for(const bad of [{...definition,periodHints:[{column:2,code:'Maria'}]},{...definition,passwordHash:'secret'},{...definition,gradeColumns:[2,'LRN']}])await expect(db.query('insert into grade_import_formats(teacher_id,fingerprint,definition) values($1,$2,$3)',[a.teacher,'e'.repeat(64),JSON.stringify(bad)])).rejects.toThrow();});});
it('commits all reviewed periods together and rolls back earlier columns on later failure',async()=>{const a=await fixture(),second=randomUUID();await db.query("insert into section_grade_periods(id,teacher_id,section_id,key,label,position) values($1,$2,$3,'period_2','Quarter 2',2)",[second,a.teacher,a.section]);await actor(a.teacher,async()=>{const groups=(last:number)=>[{periodId:a.period,rows:[{learner_id:a.learner,grade:0,expected_updated_at:null}]},{periodId:second,rows:[{learner_id:a.learner,grade:last,expected_updated_at:null}]}],apply=(g:unknown)=>db.query('select import_external_grade_columns($1,$2,$3,$4::jsonb)',[a.section,a.subject,'a'.repeat(64),JSON.stringify(g)]);await expect(apply(groups(101))).rejects.toThrow();expect((await db.query('select grade from section_grade_entries where section_id=$1',[a.section])).rows).toHaveLength(0);await expect(apply([groups(90)[0],groups(90)[0]])).rejects.toThrow(/Duplicate/);await apply(groups(90));expect((await db.query<{grade:string}>('select grade from section_grade_entries where section_id=$1 order by grade',[a.section])).rows.map(r=>Number(r.grade))).toEqual([0,90]);await expect(apply(groups(99))).rejects.toThrow(/changed/);});});
it('remembers only numeric layout metadata, scoped to the active owner',async()=>{const a=await fixture(),b=await fixture();await actor(a.teacher,async()=>{await db.query('insert into grade_import_formats(teacher_id,fingerprint,definition) values($1,$2,$3)',[a.teacher,'a'.repeat(64),JSON.stringify(format)]);await expect(db.query('insert into grade_import_formats(teacher_id,fingerprint,definition) values($1,$2,$3)',[a.teacher,'b'.repeat(64),JSON.stringify({...format,learners:['private']})])).rejects.toThrow();});await actor(b.teacher,async()=>{expect((await db.query('select * from grade_import_formats')).rows).toHaveLength(0);await expect(db.query('insert into grade_import_formats(teacher_id,fingerprint,definition) values($1,$2,$3)',[a.teacher,'c'.repeat(64),JSON.stringify(format)])).rejects.toThrow();});await db.query("update profiles set access_status='suspended' where id=$1",[a.teacher]);await actor(a.teacher,async()=>{expect((await db.query('select * from grade_import_formats')).rows).toHaveLength(0);});});
it('external imports reuse grade validation, zero, stale checks, provenance and RLS',async()=>{const a=await fixture(),b=await fixture();const apply=(grade:number|null,expected:string|null=null)=>db.query('select import_external_section_grades($1,$2,$3,$4::jsonb,$5)',[a.section,a.subject,a.period,JSON.stringify([{learner_id:a.learner,grade,expected_updated_at:expected}]),'a'.repeat(64)]);await actor(a.teacher,async()=>{await expect(apply(101)).rejects.toThrow();await expect(apply(null)).rejects.toThrow();await apply(0);const row=(await db.query<{grade:string;source_type:string;source_snapshot:unknown}>('select * from section_grade_entries where section_id=$1',[a.section])).rows[0];expect(Number(row.grade)).toBe(0);expect(row.source_type).toBe('external_import');expect(row.source_snapshot).toEqual({sha256:'a'.repeat(64)});await expect(apply(91)).rejects.toThrow(/changed/);});await actor(b.teacher,async()=>{await expect(apply(91)).rejects.toThrow();});await db.query("update sections set status='archived' where id=$1",[a.section]);await actor(a.teacher,async()=>{await expect(apply(91)).rejects.toThrow();});});
