// @vitest-environment node
import {beforeEach,it,expect,vi} from 'vitest';
import ExcelJS from 'exceljs';
vi.mock('server-only',()=>({}));
const ai=vi.hoisted(()=>({factory:vi.fn(),router:vi.fn(),propose:vi.fn(),decide:vi.fn()}));
vi.mock('@/features/assisted-workflows/provider',()=>({interpretationProvider:ai.factory,confidenceProvider:ai.router}));
import {parseWorkbook} from '@/features/report-card-templates/workbook';
import {routeGradeFile} from '@/features/assisted-workflows/grade-routing';
import {detectGradeFormat,formatFingerprint} from '@/features/assisted-workflows/grade-files';
import {periodCode,subjectKey} from '@/features/assisted-workflows/labels';
import {structuralInput,safeLabel} from '@/features/assisted-workflows/structure';
const subjects=[{id:'s',name:'Mathematics'}],periods=[1,2,3,4].map(n=>({id:`p${n}`,label:`Quarter ${n}`})),selection={format:null,subjectId:null,periodId:null};
async function workbook(headers=['Name','Q1','Q2','Q3','Q4']){const w=new ExcelJS.Workbook(),s=w.addWorksheet('Private Person');s.addRow(headers);s.addRow(['English',0,87,null,91]);return parseWorkbook(Buffer.from(await w.xlsx.writeBuffer()));}
beforeEach(()=>{vi.resetAllMocks();ai.factory.mockReturnValue({propose:ai.propose});ai.router.mockReturnValue({decide:ai.decide});ai.decide.mockResolvedValue({choice:'accept',score:1});});
it.each([['Q1',1],['Q2',2],['Q3',3],['Q4',4],['1st Quarter',1],['Second Quarter',2],['First Grading',1],['First Grading Period',1],['Quarter One',1],['Quarter Two',2],['Term 1',11],['Semester 1',21],['Midterm',31],['Final',32]])('normalizes %s without confusing period families',(label,code)=>{expect(periodCode(String(label))).toBe(code);});
it('routes a four-period workbook locally at zero AI cost',async()=>{const r=await routeGradeFile(await workbook(),'Math.xlsx',null,selection,subjects,periods);expect(r.format?.gradeColumns).toEqual([2,3,4,5]);expect(r.subjectId).toBe('s');expect(r.periodBindings).toEqual({2:'p1',3:'p2',4:'p3',5:'p4'});expect(ai.factory).not.toHaveBeenCalled();expect(ai.router).not.toHaveBeenCalled();expect(subjectKey('AP')).toBe(subjectKey('Araling Panlipunan'));});
it('reuses numeric format metadata but lets a later header identify its own period',async()=>{const first=await workbook(['Name','Q1']),later=await workbook(['Name','Second Grading']);const saved={...detectGradeFormat(first)!,periodHints:[{column:2,code:1}]};expect(formatFingerprint(first)).toBe(formatFingerprint(later));const r=await routeGradeFile(later,'Math.xlsx',saved,selection,subjects,periods);expect(r.source).toBe('remembered');expect(r.periodId).toBe('p2');expect(ai.factory).not.toHaveBeenCalled();expect(ai.router).not.toHaveBeenCalled();});
it('infers a generic grade column from its filename without an AI request',async()=>{const r=await routeGradeFile(await workbook(['Name','Grade']),'Math_First_Grading.xlsx',null,selection,subjects,periods);expect(r.periodId).toBe('p1');expect(ai.factory).not.toHaveBeenCalled();});
it('falls back to local recognition when a saved layout no longer validates',async()=>{const w=await workbook(['Name','Q1']),saved={...detectGradeFormat(w)!,sheet:19};const r=await routeGradeFile(w,'Math.xlsx',saved,selection,subjects,periods);expect(r.source).toBe('local');expect(r.periodId).toBe('p1');expect(ai.factory).not.toHaveBeenCalled();});
it('does not silently truncate a remembered layout to its first 500 learners',async()=>{const first=await workbook(['Name','Q1']),saved=detectGradeFormat(first)!,w=new ExcelJS.Workbook(),s=w.addWorksheet('Grades');s.addRow(['Name','Q1']);for(let i=0;i<501;i++)s.addRow([`Learner ${i}`,88]);const r=await routeGradeFile(await parseWorkbook(Buffer.from(await w.xlsx.writeBuffer())),'Math.xlsx',saved,selection,subjects,periods,false);expect(r.format).toBeNull();});
it('does not use remembered period meaning for an unknown changed header',async()=>{const w=await workbook(['Name','Uncertain']),saved={sheet:0,headerRow:1,nameColumn:1,gradeColumn:2,uuidColumn:null,startRow:2,endRow:2,periodHints:[{column:2,code:1}]};const r=await routeGradeFile(w,'Math.xlsx',saved,selection,subjects,periods,false);expect(r.periodId).toBeNull();});
it('validates semantic subject and period suggestions before JEV routing',async()=>{ai.propose.mockResolvedValue({format:null,subject:'Math',columns:[{column:2,period:'Q2'}]});const r=await routeGradeFile(await workbook(['Name','Grade']),'private.xlsx',null,selection,subjects,periods);expect(r).toMatchObject({subjectId:'s',periodId:'p2'});expect(ai.propose).toHaveBeenCalledOnce();expect(ai.decide).toHaveBeenCalledTimes(2);expect(ai.decide.mock.calls[0][0].candidate.field).toBe('period: quarter 2');const payload=JSON.stringify(ai.propose.mock.calls);expect(payload).not.toContain('private.xlsx');expect(payload).not.toContain('Private Person');});
it('routes JEV uncertainty to explicit review and rejection to manual selection',async()=>{ai.propose.mockResolvedValue({format:null,subject:'Math',columns:[{column:2,period:'Q2'}]});ai.decide.mockResolvedValue({choice:'review',score:0.8});expect((await routeGradeFile(await workbook(['Name','Grade']),'Math.xlsx',null,selection,subjects,periods)).source).toBe('review');ai.decide.mockResolvedValue({choice:'reject',score:0.1});expect((await routeGradeFile(await workbook(['Name','Grade']),'Math.xlsx',null,selection,subjects,periods)).periodId).toBeNull();});
it('keeps local/manual fallback on unavailable, malformed or out-of-bounds proposals',async()=>{for(const result of [null,{format:{sheet:19,headerRow:1,nameColumn:1,gradeColumn:2,gradeColumns:[2],uuidColumn:null,startRow:2,endRow:2000},subject:'Math',columns:[]}]){ai.propose.mockResolvedValue(result);const r=await routeGradeFile(await workbook(['Learner','Unknown']),'Math.xlsx',null,selection,subjects,periods);expect(r.format).toBeNull();}ai.propose.mockRejectedValue(new Error('timeout'));expect((await routeGradeFile(await workbook(['Name','Grade']),'Math.xlsx',null,selection,subjects,periods)).format).not.toBeNull();});
it('never infers a quarter as a term or uses two columns for the same destination',async()=>{const r=await routeGradeFile(await workbook(['Name','Q1']),'Math.xlsx',null,selection,subjects,[{id:'term',label:'Term 1'}],false);expect(r.periodId).toBeNull();const duplicate=await routeGradeFile(await workbook(['Name','Q1','First Quarter']),'Math.xlsx',null,selection,subjects,periods,false);expect(duplicate.periodBindings).toEqual({});expect(ai.factory).not.toHaveBeenCalled();});
it('allows structural terminology but excludes identity cells even when their text is allowlisted',async()=>{for(const label of ['Learning Areas','Quarterly Rating','General Average','Final Rating','Core Subjects','Applied Subjects','Specialized Subjects','Parent/Guardian Signature'])expect(safeLabel(label)).not.toBeNull();const safe=structuralInput(await workbook());expect(safe.sheets[0].labels.some(l=>l.address==='A2')).toBe(false);for(const privateText of ['Maria Santos','123456789012','91','11111111-1111-4111-8111-111111111111','Name: Maria'])expect(safeLabel(privateText)).toBeNull();});
it('excludes report-card identity values next to name and adviser labels',async()=>{const w=new ExcelJS.Workbook(),s=w.addWorksheet('Card');s.addRow(['Name','English']);s.addRow(['Adviser','Science']);const safe=structuralInput(await parseWorkbook(Buffer.from(await w.xlsx.writeBuffer())));expect(safe.sheets[0].labels.map(l=>l.address)).toEqual(['A1','A2']);});
