// @vitest-environment node
import { describe,it,expect,vi,afterEach } from 'vitest';
vi.mock('server-only',()=>({}));
import ExcelJS from 'exceljs';
import { parseWorkbook } from '@/features/report-card-templates/workbook';
import { structuralInput } from '@/features/assisted-workflows/structure';
import { expandProposal,fallbackMapping,proposalSchema } from '@/features/assisted-workflows/mapping';
import { JevConfidence,OpenAIInterpreter,localConfidence,interpretationProvider } from '@/features/assisted-workflows/provider';
import { matchLearner,gradePreview } from '@/features/assisted-workflows/grades';
import { detectGradeFormat,extractGrades,formatFingerprint } from '@/features/assisted-workflows/grade-files';
const hash='a'.repeat(64);
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
it('defaults to gpt-6-luna and low reasoning',async()=>{vi.stubEnv('OPENAI_API_KEY','test');vi.stubEnv('OPENAI_WORKFLOW_MODEL','');const request=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'{"fields":[],"periods":[],"tables":[]}'}]}]})));vi.stubGlobal('fetch',request);await interpretationProvider()!.propose({sheets:[]},'Map',proposalSchema);expect(JSON.parse(request.mock.calls[0][1].body)).toMatchObject({model:'gpt-6-luna',reasoning:{effort:'low'},store:false});});
async function workbook(){const w=new ExcelJS.Workbook(),s=w.addWorksheet('Maria Private 123456789012');s.getCell('A1').value='Learner name';s.getCell('D1').value='Grade';s.getCell('A2').value='Maria Santos';s.getCell('B2').value='123456789012';s.getCell('D2').value=91;s.getCell('A3').value='Juan Cruz';s.getCell('D3').value=0;s.getCell('A4').value='Ana';s.getCell('D4').value={formula:'SUM(1,2)',result:3};return parseWorkbook(Buffer.from(await w.xlsx.writeBuffer()));}
describe('provider privacy boundary',()=>{
  it('removes learner names, LRN, grades, sheet names and formula content',async()=>{const safe=JSON.stringify(structuralInput(await workbook()));for(const secret of ['Maria','Juan','123456789012','SUM','91'])expect(safe).not.toContain(secret);expect(safe).toContain('learner name');expect(safe).toContain('D4');});
  it('sends strict structure-only OpenAI request and rejects invalid output',async()=>{const request=vi.fn().mockResolvedValue(new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'{"grades":[100]}'}]}]})));const provider=new OpenAIInterpreter('test','test-model',request);await expect(provider.propose(structuralInput(await workbook()),'Map',proposalSchema)).rejects.toThrow();const body=JSON.parse(request.mock.calls[0][1].body);expect(body.store).toBe(false);expect(body.text.format.strict).toBe(true);expect(JSON.stringify(body)).not.toContain('Maria');});
  it('JEV uses the documented choice and score contract; validation always wins',async()=>{const request=vi.fn().mockResolvedValue(new Response(JSON.stringify({answers:{route:{type:'choice',choice:'accept',confidence:0.99},certainty:{type:'score',score:0.99,confidence:0.99}}})));const jev=new JevConfidence('test',request);expect((await jev.decide({valid:true,score:0.99,evidence:true})).choice).toBe('accept');expect(JSON.parse(request.mock.calls[0][1].body).model).toBe('jev-latest');expect((await jev.decide({valid:false,score:1,evidence:true})).choice).toBe('reject');expect(request).toHaveBeenCalledTimes(1);});
  it('provider outage and low confidence require teacher review',async()=>{const jev=new JevConfidence('test',vi.fn().mockRejectedValue(new Error('offline')));expect((await jev.decide({valid:true,score:1,evidence:true})).choice).toBe('review');expect((await localConfidence.decide({valid:true,score:0.2,evidence:false})).choice).toBe('review');});
});
describe('mapping proposals',()=>{
  it('expands a table through the existing mapping validator',async()=>{const w=new ExcelJS.Workbook(),s=w.addWorksheet('Front');s.getCell('A1').value='Name';s.mergeCells('B1:C1');s.getCell('B3').value='Mathematics';s.getCell('B4').value='Science';s.getCell('H5').value='End';const parsed=await parseWorkbook(Buffer.from(await w.xlsx.writeBuffer())),safe=structuralInput(parsed);const p={fields:[{key:'learner_name',location:{sheet:'sheet_0',address:'B1'},confidence:0.8}],periods:[{key:'period_1',label:'Term 1'}],tables:[{sheet:'sheet_0',subjectColumn:2,startRow:3,endRow:4,outputs:[{key:'period_1',column:4},{key:'final_grade',column:8}],confidence:0.8}]};const result=expandProposal(p,hash,parsed,safe);expect(result.fields.learner_name?.address).toBe('B1:C1');expect(result.subjects).toHaveLength(2);expect(result.subjects[1].outputs.period_1?.address).toBe('D4');expect(result.templateSha256).toBe(hash);expect(()=>expandProposal({...p,tables:[{...p.tables[0],outputs:[{key:'period_1',column:2}]}]},hash,parsed,safe)).toThrow(/overlaps/);expect(()=>expandProposal({...p,fields:[{...p.fields[0],location:{sheet:'missing',address:'B1'}}]},hash,parsed,safe)).toThrow();});
  it('provides deterministic suggestions without AI',async()=>{const safe=structuralInput(await workbook());expect(fallbackMapping(safe).fields[0].key).toBe('learner_name');});
});
describe('grade files and matching',()=>{
  it('imports original numeric precision instead of formatted display text',async()=>{const w=new ExcelJS.Workbook(),s=w.addWorksheet('Grades');s.addRow(['Learner name','Grade']);s.addRow(['Private learner',88.49]);s.getCell('B2').numFmt='0';const parsed=await parseWorkbook(Buffer.from(await w.xlsx.writeBuffer()));expect(parsed.sheet(0).cells.find(c=>c.address==='B2')?.displayValue).toBe('88');expect(extractGrades(parsed,detectGradeFormat(parsed)!)[0].grade).toBe(88.49);});
  it('recognizes the same format in a later grading period without storing values',async()=>{async function layout(term:number,grade:number){const w=new ExcelJS.Workbook(),s=w.addWorksheet('Record');s.addRow(['Learner name',`Term ${term}`]);s.addRow(['Private learner',grade]);return parseWorkbook(Buffer.from(await w.xlsx.writeBuffer()));}expect(formatFingerprint(await layout(1,88))).toBe(formatFingerprint(await layout(2,93)));});
  it('analyzes multiple workbooks without modifying any grade or calculating formulas',async()=>{const files=await Promise.all([workbook(),workbook()]);for(const file of files){const format=detectGradeFormat(file)!;const rows=extractGrades(file,format);expect(rows.map(r=>r.grade)).toEqual([91,0,3]);expect(formatFingerprint(file)).toMatch(/^[a-f0-9]{64}$/);}expect(formatFingerprint(files[0])).toBe(formatFingerprint(files[1]));});
  it('matches exact UUID/name, never LRN, and only suggests fuzzy matches',()=>{const learners=[{id:'a',display_name:'Maria Santos'},{id:'b',display_name:'Juan Cruz'}];expect(matchLearner({uuid:'a',name:'changed'},learners).id).toBe('a');expect(matchLearner({uuid:null,name:' MARIA SANTOS '},learners).id).toBe('a');expect(matchLearner({uuid:null,name:'Maria D. Santos'},learners)).toMatchObject({id:null,candidates:['a'],certain:false});expect(matchLearner({uuid:null,name:'123456789012'},learners).id).toBeNull();expect(matchLearner({uuid:null,name:'Maria Santos'},[...learners,{id:'c',display_name:'Maria Santos'}]).id).toBeNull();});
  it('flags existing grades, invalid rows and duplicate identities',()=>{const learners=[{id:'a',display_name:'Maria Santos'}],rows=[{row:2,name:'Maria Santos',uuid:null,grade:91,invalid:false}];const entries=[{learner_id:'a',section_subject_id:'s',period_id:'p',grade:88,source_type:'manual' as const,source_class_id:null,source_reference:null,source_snapshot:null,updated_at:'now'}];expect(gradePreview(rows,learners,entries,'s','p')[0].kind).toBe('conflict');expect(gradePreview([...rows,{...rows[0],row:3}],learners,entries,'s','p').every(r=>r.kind==='duplicate')).toBe(true);expect(gradePreview([{...rows[0],grade:null,invalid:true}],learners,entries,'s','p')[0].kind).toBe('invalid');expect(entries[0].grade).toBe(88);});
});
