// @vitest-environment node
import { beforeEach,it,expect,vi } from 'vitest';
import ExcelJS from 'exceljs';
vi.mock('server-only',()=>({}));
const mocks=vi.hoisted(()=>({access:vi.fn(),section:vi.fn(),book:vi.fn(),rpc:vi.fn(),from:vi.fn()}));
vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
vi.mock('@/features/sections/action-helpers',()=>({sectionAccess:mocks.access,requireSection:mocks.section,SectionError:class extends Error{}}));
vi.mock('@/features/gradebook/data',()=>({readGradebook:mocks.book}));
vi.mock('@/features/assisted-workflows/provider',()=>({interpretationProvider:()=>null}));
import { analyzeGradeFile,applyGradeFile } from '@/features/assisted-workflows/grade-actions';
const id='11111111-1111-4111-8111-111111111111',subject='22222222-2222-4222-8222-222222222222',period='33333333-3333-4333-8333-333333333333',learner='44444444-4444-4444-8444-444444444444';
const book=()=>({learners:[{id:learner,display_name:'Alice Test',status:'active'}],subjects:[{id:subject,name:'Science',status:'active'}],periods:[{id:period,label:'Term 1',status:'active'}],entries:[] as {learner_id:string;section_subject_id:string;period_id:string;grade:number;updated_at:string;source_type:string}[],classes:[]});
beforeEach(()=>{vi.clearAllMocks();const chain={select:vi.fn().mockReturnThis(),eq:vi.fn().mockReturnThis(),maybeSingle:vi.fn().mockResolvedValue({data:null,error:null}),upsert:vi.fn().mockResolvedValue({error:null})};mocks.from.mockReturnValue(chain);mocks.access.mockResolvedValue({user:{id},supabase:{from:mocks.from,rpc:mocks.rpc}});mocks.section.mockResolvedValue({status:'active'});mocks.book.mockResolvedValue(book());mocks.rpc.mockResolvedValue({error:null});});
async function form(){const w=new ExcelJS.Workbook(),s=w.addWorksheet('Grades');s.getCell('A1').value='Learner name';s.getCell('B1').value='Term 1';s.getCell('A2').value='Alice Test';s.getCell('B2').value=91;const f=new FormData();f.set('file',new File([new Uint8Array(await w.xlsx.writeBuffer())],'Science.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));f.set('selection',JSON.stringify({sectionId:id,subjectId:null,periodId:null,format:null,resolutions:{}}));return f;}
it('analysis is read-only and import writes only extracted grades after explicit approval',async()=>{const f=await form(),r=await analyzeGradeFile(f);expect(r.ok).toBe(true);if(!r.ok)return;expect(mocks.rpc).not.toHaveBeenCalled();expect(r.data.rows[0]).toMatchObject({learnerId:learner,incoming:91,kind:'ready'});f.set('selection',JSON.stringify(r.data.selection));f.set('approval',JSON.stringify({digest:r.data.digest,confirmed:true,useIncoming:[],skip:[],remember:true}));expect((await applyGradeFile(f)).ok).toBe(true);expect(mocks.rpc.mock.calls[0][1].p_rows[0].grade).toBe(91);});
it('rejects changed grades after preview and never writes',async()=>{const f=await form(),r=await analyzeGradeFile(f);if(!r.ok)throw new Error(r.error);const changed=book();changed.entries=[{learner_id:learner,section_subject_id:subject,period_id:period,grade:88,updated_at:'2026-10-07T01:00:00Z',source_type:'manual'}];mocks.book.mockResolvedValue(changed);f.set('selection',JSON.stringify(r.data.selection));f.set('approval',JSON.stringify({digest:r.data.digest,confirmed:true,useIncoming:[],skip:[],remember:false}));expect((await applyGradeFile(f)).ok).toBe(false);expect(mocks.rpc).not.toHaveBeenCalled();});
it('requires explicit existing-grade conflict resolution',async()=>{const changed=book();changed.entries=[{learner_id:learner,section_subject_id:subject,period_id:period,grade:88,updated_at:'2026-10-07T01:00:00Z',source_type:'manual'}];mocks.book.mockResolvedValue(changed);const f=await form(),r=await analyzeGradeFile(f);if(!r.ok)throw new Error(r.error);expect(r.data.rows[0].kind).toBe('conflict');f.set('selection',JSON.stringify(r.data.selection));f.set('approval',JSON.stringify({digest:r.data.digest,confirmed:true,useIncoming:[],skip:[],remember:false}));expect((await applyGradeFile(f)).ok).toBe(false);expect(mocks.rpc).not.toHaveBeenCalled();f.set('approval',JSON.stringify({digest:r.data.digest,confirmed:true,useIncoming:[2],skip:[],remember:false}));expect((await applyGradeFile(f)).ok).toBe(true);});
it('rejects client-supplied grade modifications and inactive access',async()=>{const f=await form();f.set('selection',JSON.stringify({sectionId:id,subjectId:subject,periodId:period,format:null,resolutions:{},grades:[100]}));expect((await analyzeGradeFile(f)).ok).toBe(false);expect(mocks.rpc).not.toHaveBeenCalled();mocks.access.mockRejectedValue(new Error('unauthorized'));expect((await analyzeGradeFile(await form())).ok).toBe(false);});
it('imports multiple periods atomically with independent conflicts, zero and blank protection',async()=>{
  const second='55555555-5555-4555-8555-555555555555',third='66666666-6666-4666-8666-666666666666',b=book();b.periods=[{id:period,label:'Quarter 1',status:'active'},{id:second,label:'Quarter 2',status:'active'},{id:third,label:'Quarter 3',status:'active'}];b.entries=[{learner_id:learner,section_subject_id:subject,period_id:period,grade:88,updated_at:'2026-10-07T01:00:00Z',source_type:'manual'},{learner_id:learner,section_subject_id:subject,period_id:third,grade:92,updated_at:'2026-10-07T01:00:00Z',source_type:'manual'}];mocks.book.mockResolvedValue(b);
  const w=new ExcelJS.Workbook(),s=w.addWorksheet('Grades');s.addRow(['Name','Q1','Q2','Q3']);s.addRow(['Alice Test',91,0,null]);const f=await form();f.set('file',new File([new Uint8Array(await w.xlsx.writeBuffer())],'Science.xlsx'));const preview=await analyzeGradeFile(f);if(!preview.ok)throw new Error(preview.error);expect(preview.data.rows.map(r=>r.kind)).toEqual(['conflict','ready','missing']);expect(new Set(preview.data.rows.map(r=>r.row)).size).toBe(3);f.set('selection',JSON.stringify(preview.data.selection));
  const approve=(useIncoming:number[])=>f.set('approval',JSON.stringify({digest:preview.data.digest,confirmed:true,useIncoming,skip:[],remember:true}));approve([]);expect((await applyGradeFile(f)).ok).toBe(false);expect(mocks.rpc).not.toHaveBeenCalled();approve([preview.data.rows[0].row]);expect((await applyGradeFile(f)).ok).toBe(true);expect(mocks.rpc).toHaveBeenCalledWith('import_external_grade_columns',expect.objectContaining({p_groups:[{periodId:period,rows:[{learner_id:learner,grade:91,expected_updated_at:'2026-10-07T01:00:00Z'}]},{periodId:second,rows:[{learner_id:learner,grade:0,expected_updated_at:null}]}]}));
  mocks.rpc.mockClear();b.entries[1].grade=93;expect((await applyGradeFile(f)).ok).toBe(false);expect(mocks.rpc).not.toHaveBeenCalled();
});
