// @vitest-environment node
import {beforeEach,it,expect,vi} from 'vitest';
import ExcelJS from 'exceljs';
vi.mock('server-only',()=>({}));
const mocks=vi.hoisted(()=>({access:vi.fn(),owned:vi.fn(),bytes:vi.fn(),saved:vi.fn(),factory:vi.fn(),router:vi.fn(),propose:vi.fn(),decide:vi.fn()}));
vi.mock('@/features/report-card-templates/data',()=>({templateAccess:mocks.access,ownedTemplate:mocks.owned,originalBytes:mocks.bytes,TemplateError:class extends Error{}}));
vi.mock('@/features/report-card-mappings/data',()=>({readMapping:mocks.saved}));
vi.mock('@/features/assisted-workflows/provider',()=>({interpretationProvider:mocks.factory,confidenceProvider:mocks.router}));
import {analyzeTemplate} from '@/features/assisted-workflows/mapping-actions';
const sha='a'.repeat(64);
beforeEach(()=>{vi.resetAllMocks();mocks.access.mockResolvedValue({});mocks.owned.mockResolvedValue({status:'active',file_sha256:sha});mocks.saved.mockResolvedValue(null);mocks.factory.mockReturnValue({propose:mocks.propose});mocks.router.mockReturnValue({decide:mocks.decide});mocks.decide.mockResolvedValue({choice:'review',score:0.7});});
async function fixture(ambiguous=false){const w=new ExcelJS.Workbook(),s=w.addWorksheet('Private sheet');if(ambiguous){s.getCell('B10').value='Quarterly Rating';s.getCell('B11').value='Science';}else{for(const [cell,value]of Object.entries({A1:'Learner name',D1:'Grade level',G1:'Section',J1:'School year',B10:'Learning Areas',D10:'Q1',E10:'Q2',F10:'Q3',G10:'Q4',B11:'Science',B12:'Mathematics'}))s.getCell(cell).value=value;}s.getCell('L20').value='End';mocks.bytes.mockResolvedValue(Buffer.from(await w.xlsx.writeBuffer()));}
it('makes zero provider calls for obvious labels and a local table',async()=>{await fixture();const r=await analyzeTemplate('template');if(!r.ok)throw new Error(r.error);expect(r.data.source).toBe('local');expect(r.data.definition.subjects).toHaveLength(2);expect(r.data.definition.periods).toHaveLength(4);expect(r.data.issues).toEqual(['table']);expect(mocks.factory).not.toHaveBeenCalled();expect(mocks.router).not.toHaveBeenCalled();});
it('reuses an already confirmed mapping before constructing providers',async()=>{await fixture();const first=await analyzeTemplate('template');if(!first.ok)throw new Error(first.error);mocks.saved.mockResolvedValue({status:'reviewed',mapping_definition:first.data.definition});const second=await analyzeTemplate('template');if(!second.ok)throw new Error(second.error);expect(second.data.source).toBe('remembered');expect(second.data.definition).toEqual(first.data.definition);expect(second.data.issues).toEqual([]);expect(mocks.factory).not.toHaveBeenCalled();});
it('expands a valid AI table through the existing validator and requires grouped approval',async()=>{await fixture(true);mocks.propose.mockResolvedValue({fields:[{key:'learner_name',location:{sheet:'sheet_0',address:'B1'},confidence:0.8}],periods:[{key:'period_1',label:'Quarter 1'}],tables:[{sheet:'sheet_0',subjectColumn:2,startRow:11,endRow:11,outputs:[{key:'period_1',column:4}],confidence:0.8}]});const r=await analyzeTemplate('template');if(!r.ok)throw new Error(r.error);expect(r.data.source).toBe('ai');expect(r.data.definition.subjects[0].outputs.period_1?.address).toBe('D11');expect(r.data.issues).toContain('table');expect(r.data.issues).toContain('field:learner_name');expect(mocks.decide).toHaveBeenCalledTimes(2);mocks.decide.mockResolvedValue({choice:'reject',score:0.1});const rejected=await analyzeTemplate('template');if(!rejected.ok)throw new Error(rejected.error);expect(rejected.data.definition.subjects).toHaveLength(0);expect(rejected.data.issues).toContain('missing:table');});
it('rejects invalid proposals and keeps manual fallback after an outage',async()=>{await fixture(true);mocks.propose.mockResolvedValue({fields:[{key:'learner_name',location:{sheet:'sheet_0',address:'X9999'},confidence:1}],periods:[],tables:[]});const r=await analyzeTemplate('template');if(!r.ok)throw new Error(r.error);expect(r.data.source).toBe('local');expect(r.data.definition.fields.learner_name).toBeUndefined();expect(mocks.router).not.toHaveBeenCalled();mocks.propose.mockRejectedValue(new Error('timeout'));expect((await analyzeTemplate('template')).ok).toBe(true);});
