import { afterEach,beforeEach,it,expect,vi } from 'vitest';
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import type { GradebookData } from '@/features/gradebook/data';
const mocks=vi.hoisted(()=>({analyze:vi.fn(),apply:vi.fn(),discover:vi.fn(),sync:vi.fn(),template:vi.fn(),save:vi.fn(),push:vi.fn(),refresh:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:mocks.push,refresh:mocks.refresh})}));
vi.mock('@/features/assisted-workflows/grade-actions',()=>({analyzeGradeFile:mocks.analyze,applyGradeFile:mocks.apply}));
vi.mock('@/features/assisted-workflows/sync-actions',()=>({discoverClassSync:mocks.discover,applyClassSync:mocks.sync}));
vi.mock('@/features/assisted-workflows/mapping-actions',()=>({analyzeTemplate:mocks.template}));
vi.mock('@/features/report-card-mappings/actions',()=>({saveMapping:mocks.save}));
import { GradeInbox } from '@/features/assisted-workflows/inbox';
import { MappingReview } from '@/features/assisted-workflows/mapping-review';
const book={section:{id:'section',name:'Rizal',status:'active'},subjects:[{id:'subject',name:'Science',status:'active'}],periods:[{id:'period',label:'Term 1',status:'active'}],learners:[{id:'learner',display_name:'Maria',status:'active'}],entries:[],classes:[]} as unknown as GradebookData;
beforeEach(()=>{vi.clearAllMocks();mocks.discover.mockResolvedValue({ok:true,data:{proposals:[],issues:[]}});mocks.apply.mockResolvedValue({ok:true,data:{count:1,remembered:true}});});afterEach(cleanup);
it('keeps grade conflicts blocked until explicitly resolved, then imports the reviewed batch',async()=>{
  mocks.analyze.mockResolvedValue({ok:true,data:{selection:{sectionId:'section',subjectId:'subject',periodId:'period',format:{sheet:0,headerRow:1,nameColumn:1,gradeColumn:2,uuidColumn:null,startRow:2,endRow:2},resolutions:{},sectionConfirmed:false},rows:[{row:2,name:'Maria',incoming:91,learnerId:'learner',candidates:[],current:{grade:88},kind:'conflict'}],source:'local',sectionMismatch:null,digest:'a'.repeat(64),sheets:[{index:0,name:'Grades',rows:2,columns:2}]}});
  const {container}=render(<GradeInbox book={book}/>);fireEvent.change(container.querySelector('input[type=file]')!,{target:{files:[new File(['xlsx'],'Science.xlsx')]}});await screen.findByRole('button',{name:'Review 1 issues'});expect(screen.queryByText(/Current: 88/)).not.toBeInTheDocument();await waitFor(()=>expect(screen.getByRole('button',{name:'Review 1 issues'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Review 1 issues'}));await screen.findByText('Maria · Current: 88 · Incoming: 91');expect(screen.getByRole('button',{name:'Import reviewed files (0)'})).toBeDisabled();expect(mocks.apply).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Use 91'}));fireEvent.click(screen.getByRole('button',{name:'Import reviewed files (1)'}));await waitFor(()=>expect(mocks.apply).toHaveBeenCalledTimes(1));const approval=JSON.parse(mocks.apply.mock.calls[0][0].get('approval'));expect(approval).toMatchObject({confirmed:true,useIncoming:[2]});await screen.findByText('Science.xlsx · Imported');
});
it('shows only template exceptions and saves after review, never on analysis',async()=>{
  const definition={formatVersion:1,templateSha256:'a'.repeat(64),fields:{learner_name:{sheet:'Front',address:'B1'}},periods:[],subjects:[]};mocks.template.mockResolvedValue({ok:true,data:{definition,proposal:{fields:[],tables:[],periods:[]},issues:['field:learner_name'],source:'local'}});mocks.save.mockResolvedValue({ok:true,data:{}});render(<MappingReview id="template" name="Report card" initial={null}/>);fireEvent.click(screen.getByRole('button',{name:'Analyze template'}));await screen.findByText('1 things need attention');await screen.findByRole('button',{name:'Save mapping'});expect(mocks.save).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Save mapping'})).toBeDisabled();expect(screen.queryByRole('button',{name:'Looks right'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Review 1 issue'}));fireEvent.click(screen.getByRole('button',{name:'Looks right'}));fireEvent.click(screen.getByRole('button',{name:'Save mapping'}));await waitFor(()=>expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({definition,status:'reviewed',expectedId:null,revision:0})));
});
