// @vitest-environment node
import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,it,expect} from 'vitest';
import type {PGlite} from '@electric-sql/pglite';
import {database,migrate} from './helpers/database';
let db:PGlite;
const metadata={formatVersion:1,sheets:[{name:'Blank',index:0,state:'visible',rowExtent:1,columnExtent:1,mergeCount:0,formulaCount:0,hasImages:false,hasExternalReferences:false,hasPrintArea:false,hasFreezePane:false,truncated:false}]};
beforeAll(async()=>{db=await database();await db.exec('grant select,insert,update,delete on storage.objects to authenticated');},30000);
afterAll(async()=>{await db?.close();});
async function owner(){const id=randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'template@example.com',now())",[id]);await db.query("update profiles set access_status='active' where id=$1",[id]);return id;}
async function actor(id:string,fn:()=>Promise<void>,role='authenticated'){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);try{await fn();}finally{await db.exec('reset role');}}
async function insert(teacher:string,id=randomUUID(),hash='a'.repeat(64),meta:unknown=metadata){await db.query("insert into report_card_templates(id,teacher_id,name,original_filename,storage_path,mime_type,file_size_bytes,file_sha256,sheet_count,workbook_metadata) values($1,$2,'Blank','blank.xlsx',$3,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',100,$4,1,$5::jsonb)",[id,teacher,`${teacher}/${id}/source.xlsx`,hash,JSON.stringify(meta)]);return id;}
it('full chain installs private bounded bucket and only structural template data',async()=>{expect((await db.query("select public,file_size_limit from storage.buckets where id='report-card-templates'")).rows).toEqual([{public:false,file_size_limit:10485760}]);expect((await db.query<{column_name:string}>("select column_name from information_schema.columns where table_name='report_card_templates'")).rows.map(r=>r.column_name)).not.toContain('section_id');});
it('allows rename/archive, prevents overwriting any original fields, and enforces active hash uniqueness',async()=>{const teacher=await owner();await actor(teacher,async()=>{const id=await insert(teacher);await expect(insert(teacher)).rejects.toThrow(/unique/);await db.query("update report_card_templates set name='Renamed',status='archived' where id=$1",[id]);await insert(teacher);await expect(db.query("update report_card_templates set status='active' where id=$1",[id])).rejects.toThrow(/unique/);await expect(db.query("update report_card_templates set file_sha256=$1 where id=$2",['b'.repeat(64),id])).rejects.toThrow(/permission/);});const id=await insert(teacher,randomUUID(),'c'.repeat(64));await expect(db.query("update report_card_templates set original_filename='other.xlsx' where id=$1",[id])).rejects.toThrow(/immutable/);});
it.each(['pending','suspended','unverified','other','admin','anon'])('denies %s reads and writes',async state=>{const teacher=await owner(),id=await insert(teacher);let acting=teacher;if(['pending','suspended'].includes(state))await db.query('update profiles set access_status=$1 where id=$2',[state,teacher]);if(state==='unverified')await db.query('update auth.users set email_confirmed_at=null where id=$1',[teacher]);if(state==='other'||state==='admin'){acting=await owner();if(state==='admin')await db.query("update profiles set role='admin' where id=$1",[acting]);}await actor(acting,async()=>{const read=db.query('select * from report_card_templates where id=$1',[id]);if(state==='anon')await expect(read).rejects.toThrow(/permission/);else expect((await read).rows).toHaveLength(0);await expect(insert(teacher)).rejects.toThrow();},state==='anon'?'anon':'authenticated');});
it('source storage prevents overwrite and recreation after registration',async()=>{const teacher=await owner(),id=randomUUID(),path=`${teacher}/${id}/source.xlsx`;await actor(teacher,async()=>{await db.query("insert into storage.objects(id,bucket_id,name) values($1,'report-card-templates',$2)",[randomUUID(),path]);await insert(teacher,id);expect((await db.query("update storage.objects set name=$1 where name=$1 returning name",[path])).rows).toHaveLength(0);await db.query('delete from storage.objects where name=$1',[path]);await expect(db.query("insert into storage.objects(id,bucket_id,name) values($1,'report-card-templates',$2)",[randomUUID(),path])).rejects.toThrow(/row-level security/);});});
it.each([{...metadata,cellValues:['private']},{...metadata,sheets:[{...metadata.sheets[0],hasImages:null}]},{...metadata,sheets:[{...metadata.sheets[0],rowExtent:null}]},{...metadata,sheets:[{...metadata.sheets[0],state:null}]}])('rejects unsafe or null metadata',async meta=>{await expect(insert(await owner(),randomUUID(),'a'.repeat(64),meta)).rejects.toThrow();});
it('preserves populated Class scores, attendance, printed grades and sync history through 0018',async()=>{
  const old=await database(17);try{
    const teacher=randomUUID(),cid=randomUUID(),learner=randomUUID(),assessment=randomUUID();
    await old.query("insert into auth.users(id,email,email_confirmed_at) values($1,'upgrade-class@example.com',now())",[teacher]);
    await old.query("insert into classes(id,teacher_id,name,subject,grade_level,school_year) values($1,$2,'Synthetic class','Subject','Grade 8','2026')",[cid,teacher]);
    await old.query("insert into learners(id,teacher_id,display_name) values($1,$2,'Synthetic learner')",[learner,teacher]);
    await old.query('insert into class_enrollments(class_id,learner_id) values($1,$2)',[cid,learner]);
    await old.query("insert into assessments(id,class_id,title,kind,source,total_points,term,component) values($1,$2,'Task','mixed','manual',100,1,'performance_task')",[assessment,cid]);
    await old.query("insert into submissions(assessment_id,learner_id,score,max_score,review_status) values($1,$2,88,100,'confirmed')",[assessment,learner]);
    await old.query('insert into teacher_term_grades(class_id,learner_id,term,term_grade) values($1,$2,1,89)',[cid,learner]);
    await old.query("insert into attendance_entries(class_id,learner_id,attendance_date,status) values($1,$2,'2026-10-05','present')",[cid,learner]);
    await old.query("insert into class_record_sync_versions(class_id,teacher_id,request_id,version_number,filename,changes,before_snapshot,after_snapshot,uploaded_snapshot) values($1,$2,$3,1,'synthetic.xlsx','[]','{}','{}','{}')",[cid,teacher,randomUUID()]);
    const tables=(await old.query<{tablename:string}>("select tablename from pg_tables where schemaname='public' order by tablename")).rows;
    const snapshot=()=>Promise.all(tables.map(t=>old.query(`select to_jsonb(t) row from public.${t.tablename} t order by to_jsonb(t)::text`)));
    const before=await snapshot();await migrate(old,18,18);expect(await snapshot()).toEqual(before);
  }finally{await old.close();}
},30000);
it('populated 0017 upgrades without changing existing academic rows',async()=>{const old=await database(17);try{const teacher=randomUUID(),section=randomUUID(),learner=randomUUID(),subject=randomUUID(),period=randomUUID();await old.query("insert into auth.users(id,email,email_confirmed_at) values($1,'upgrade@example.com',now())",[teacher]);await old.query("insert into sections(id,teacher_id,name,grade_level,school_year) values($1,$2,'Section','Grade 8','2026')",[section,teacher]);await old.query("insert into learners(id,teacher_id,display_name) values($1,$2,'Synthetic fixture')",[learner,teacher]);await old.query('insert into section_enrollments(teacher_id,section_id,learner_id) values($1,$2,$3)',[teacher,section,learner]);await old.query("insert into section_subjects(id,teacher_id,section_id,name,position) values($1,$2,$3,'Subject',1)",[subject,teacher,section]);await old.query("insert into section_grade_periods(id,teacher_id,section_id,key,label,position) values($1,$2,$3,'period_1','Period',1)",[period,teacher,section]);await old.query("insert into section_grade_entries(teacher_id,section_id,learner_id,section_subject_id,period_id,grade,source_type) values($1,$2,$3,$4,$5,88,'manual')",[teacher,section,learner,subject,period]);const tables=['sections','learners','section_enrollments','section_subjects','section_grade_periods','section_grade_entries','classes','assessments','submissions','attendance_entries','class_record_sync_versions'];const before=await Promise.all(tables.map(t=>old.query(`select * from ${t}`)));await migrate(old,18,18);const after=await Promise.all(tables.map(t=>old.query(`select * from ${t}`)));expect(after).toEqual(before);}finally{await old.close();}},30000);
