// @vitest-environment node
import {it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
vi.mock('server-only',()=>({}));
import {parseWorkbook} from '@/features/report-card-templates/workbook';
import {validateDefinition,assignments,clearAssignment,mappingWarnings} from '@/features/report-card-mappings/model';
import {mappingWorkbook,mappingDefinition} from './helpers/mapping-fixture';
async function setup(){const bytes=await mappingWorkbook(),hash=createHash('sha256').update(bytes).digest('hex'),structure=await parseWorkbook(bytes);return {bytes,hash,structure,definition:mappingDefinition(hash)};}
it.each([3,4,8])('supports %i explicit generic periods and arbitrary subject layouts',async count=>{const f=await setup(),d=mappingDefinition(f.hash,count);if(count===8)d.subjects[0].outputs=Object.fromEntries(d.periods.map((p,i)=>[p.key,{sheet:'Front page',address:`D${16+i}`}])) as typeof d.subjects[0]['outputs'];d.periods[0].label='Midyear custom';const result=validateDefinition(d,f.hash,f.structure);expect(result.periods).toHaveLength(count);expect(result.periods[0].label).toBe('Midyear custom');expect(result.subjects[0].key).toBe(d.subjects[0].key);expect(result).not.toHaveProperty('section_id');});
it('canonicalizes merged cell selection, retains exact sheet names and preserves source SHA',async()=>{const f=await setup(),before=Buffer.from(f.bytes);f.definition.fields.learner_name={sheet:'Front page',address:'D8'};const result=validateDefinition(f.definition,f.hash,f.structure);expect(result.fields.learner_name).toEqual({sheet:'Front page',address:'C8:F8'});expect(createHash('sha256').update(f.bytes).digest('hex')).toBe(f.hash);expect(f.bytes.equals(before)).toBe(true);});
it('allows explicitly chosen hidden sheets and rectangular ranges',async()=>{const f=await setup();f.definition.fields.school_id={sheet:'Hidden lookup',address:'A1:B2'};expect(validateDefinition(f.definition,f.hash,f.structure).fields.school_id).toEqual({sheet:'Hidden lookup',address:'A1:B2'});});
it.each(['A0','XFE1','A1:C3:E5','B3:A1','A31','J1'])('rejects invalid or unsupported coordinate %s',async address=>{const f=await setup();f.definition.fields.school_id={sheet:'Front page',address};expect(()=>validateDefinition(f.definition,f.hash,f.structure)).toThrow();});
it('rejects missing or differently cased sheets',async()=>{const f=await setup();f.definition.fields.school_id={sheet:'front page',address:'A1'};expect(()=>validateDefinition(f.definition,f.hash,f.structure)).toThrow(/does not exist/);});
it('rejects non-worksheet sheet types even when a structural summary exists',async()=>{const f=await setup();f.structure.worksheetNames=[];expect(()=>validateDefinition(f.definition,f.hash,f.structure)).toThrow(/Only worksheet cells/);});
it.each(['C8','D8','C8:F8','B7:D9'])('rejects overlapping merged destinations %s',async address=>{const f=await setup();f.definition.fields.school_name={sheet:'Front page',address};expect(()=>validateDefinition(f.definition,f.hash,f.structure)).toThrow(/overlap|merged/);});
it('rejects unmerged range intersections across scalar and grade outputs',async()=>{const f=await setup();f.definition.fields.general_remarks={sheet:'Front page',address:'C14:F16'};expect(()=>validateDefinition(f.definition,f.hash,f.structure)).toThrow(/overlap/);});
it('rejects duplicate period/subject keys and undefined period output',async()=>{const f=await setup();const duplicate=structuredClone(f.definition);duplicate.periods.push(duplicate.periods[0]);expect(()=>validateDefinition(duplicate,f.hash,f.structure)).toThrow(/unique/);const subjects=structuredClone(f.definition);subjects.subjects.push(subjects.subjects[0]);expect(()=>validateDefinition(subjects,f.hash,f.structure)).toThrow(/unique/);f.definition.subjects[0].outputs.period_8={sheet:'Front page',address:'G16'};expect(()=>validateDefinition(f.definition,f.hash,f.structure)).toThrow(/Define/);});
it('rejects source mismatch and actual values or extra unknown data',async()=>{const f=await setup();expect(()=>validateDefinition(f.definition,'f'.repeat(64),f.structure)).toThrow(/different source/);expect(()=>validateDefinition({...f.definition,lrn:'123456789012'},f.hash,f.structure)).toThrow();expect(()=>validateDefinition({...f.definition,fields:{lrn:{sheet:'Front page',address:'A1',value:'123456789012'}}},f.hash,f.structure)).toThrow();});
it('allows partial mappings and clearing individual fields without a universal completeness requirement',async()=>{const f=await setup();const partial={...f.definition,periods:[],subjects:[],fields:{lrn:{sheet:'Front page',address:'A1'}}};const checked=validateDefinition(partial,f.hash,f.structure);expect(mappingWarnings(checked)).toContain('Learner Name is not mapped.');expect(assignments(clearAssignment(checked,'field:lrn'))).toHaveLength(0);});
