// @vitest-environment node
import {beforeAll,afterAll,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {PGlite} from '@electric-sql/pglite';
import {database} from './helpers/database';
import {mappingDefinition} from './helpers/mapping-fixture';
import type {GenerationProfile,GenerationSnapshot} from '@/features/report-card-generation/model';
import {valuesForLearner,verifyProfile,validateBindings} from '@/features/report-card-generation/model';
let db:PGlite;const hash='a'.repeat(64);
beforeAll(async()=>{db=await database();},30000);afterAll(async()=>{await db?.close();});
async function owner(){const id=randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'generation@example.com',now())",[id]);await db.query("update profiles set access_status='active',full_name='Adviser García' where id=$1",[id]);return id;}
async function actor<T>(id:string,fn:()=>Promise<T>,role='authenticated'){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);try{return await fn();}finally{await db.exec('reset role');}}
async function fixture(count=3){const teacher=await owner(),section=randomUUID(),template=randomUUID(),learner=randomUUID(),inactive=randomUUID(),subject=randomUUID(),def=mappingDefinition(hash,count),periods=Array.from({length:count},()=>randomUUID());
  await db.query("insert into sections(id,teacher_id,name,grade_level,school_year,is_adviser) values($1,$2,'Rizal','Grade 8','2026-2027',true)",[section,teacher]);
  for(const [i,id]of periods.entries())await db.query("insert into section_grade_periods(id,teacher_id,section_id,key,label,position) values($1,$2,$3,$4,$5,$6)",[id,teacher,section,`period_${i+1}`,`Different ${i}`,i+1]);
  await db.query("insert into section_subjects(id,teacher_id,section_id,name,position) values($1,$2,$3,'Different subject',1)",[subject,teacher,section]);
  for(const id of [learner,inactive]){await db.query("insert into learners(id,teacher_id,display_name) values($1,$2,'José 李')",[id,teacher]);await db.query('insert into section_enrollments(teacher_id,section_id,learner_id,status) values($1,$2,$3,$4)',[teacher,section,id,id===learner?'active':'inactive']);}
  await db.query("insert into report_card_templates(id,teacher_id,name,original_filename,storage_path,mime_type,file_size_bytes,file_sha256,sheet_count,workbook_metadata) values($1,$2,'Test','blank.xlsx',$3,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',100,$4,1,$5)",[template,teacher,`${teacher}/${template}/source.xlsx`,hash,{formatVersion:1,sheets:[{name:'Front page',index:0,state:'visible',rowExtent:30,columnExtent:9,mergeCount:1,formulaCount:0,hasImages:false,hasExternalReferences:false,hasPrintArea:false,hasFreezePane:false,truncated:false}]}]);
  const mapping=await actor(teacher,async()=>{const r=await db.query<{m:{id:string;revision:number}}>("select to_jsonb(save_report_card_mapping($1,$2,null,0,'reviewed')) m",[template,def]);await db.query('select save_section_grades($1,$2,$3,$4)',[section,subject,periods[0],[{learner_id:learner,grade:0,expected_updated_at:null}]]);return r.rows[0].m;});
  const bindings={periodBindings:Object.fromEntries(def.periods.map((p,i)=>[p.key,periods[count-1-i]])),subjectBindings:{[def.subjects[0].key]:subject}};
  return {teacher,section,template,learner,inactive,subject,periods,def,mapping,bindings};
}
type F=Awaited<ReturnType<typeof fixture>>;
async function save(f:F,id:string|null=null,revision=0,extra:Partial<F>={}){const p={...f,...extra};return (await db.query<{p:GenerationProfile}>('select to_jsonb(save_generation_profile($1,$2,$3,$4,$5,$6,$7,$8)) p',[p.section,p.template,p.mapping.id,p.mapping.revision,hash,p.bindings,id,revision])).rows[0].p;}
async function snapshot(f:F){return (await db.query<{s:GenerationSnapshot}>('select report_card_generation_snapshot($1,$2) s',[f.section,f.template])).rows[0].s;}
it.each([3,4])('creates/updates %s-period explicit UUID bindings; reversed periods, zero, missing and inactive membership remain correct',async count=>{const f=await fixture(count);await actor(f.teacher,async()=>{const first=await save(f);expect(first.revision).toBe(1);const s=await snapshot(f);expect(s.learners.map(l=>l.id)).toEqual([f.learner]);expect(s.adviserName).toBe('Adviser García');const values=valuesForLearner(s,f.def,s.learners[0]);expect(values.find(v=>v.id.endsWith(`period_${count}`))?.value).toBe(0);expect(values.find(v=>v.id.endsWith('period_1'))?.value).toBeNull();expect(values.find(v=>v.id.endsWith(':label'))?.value).toBe('Different subject');const next=await save(f,first.id,1);expect(next.revision).toBe(2);await expect(save(f,first.id,1)).rejects.toMatchObject({code:'PT409'});await expect(save(f)).rejects.toMatchObject({code:'PT409'});expect(()=>valuesForLearner(s,f.def,{id:f.inactive,display_name:'Inactive'})).toThrow(/active/);});});
it.each(['other','admin','pending','suspended','unverified','anon'])('denies %s profile read/save/snapshot',async state=>{const f=await fixture();await actor(f.teacher,()=>save(f));let who=f.teacher;if(state==='other'||state==='admin'){who=await owner();if(state==='admin')await db.query("update profiles set role='admin' where id=$1",[who]);}if(state==='pending'||state==='suspended')await db.query('update profiles set access_status=$1 where id=$2',[state,who]);if(state==='unverified')await db.query('update auth.users set email_confirmed_at=null where id=$1',[who]);await actor(who,async()=>{const read=db.query('select * from report_card_generation_profiles where section_id=$1',[f.section]);if(state==='anon'){await expect(read).rejects.toThrow(/permission/);await expect(snapshot(f)).rejects.toThrow(/permission/);}else{expect((await read).rows).toHaveLength(0);expect(await snapshot(f)).toBeNull();}await expect(save(f)).rejects.toThrow();},state==='anon'?'anon':'authenticated');});
it('rejects stale mappings, source hashes, foreign/inactive IDs, unconfirmed labels and LRN payloads',async()=>{const f=await fixture(),other=await fixture();await actor(f.teacher,async()=>{await expect(save(f,null,0,{mapping:{...f.mapping,revision:2}})).rejects.toMatchObject({code:'PT409'});await expect(db.query('select save_generation_profile($1,$2,$3,1,$4,$5,null,0)',[f.section,f.template,f.mapping.id,'b'.repeat(64),f.bindings])).rejects.toMatchObject({code:'PT409'});await expect(save(f,null,0,{bindings:{...f.bindings,subjectBindings:{[f.def.subjects[0].key]:other.subject}}})).rejects.toThrow(/subject/);await expect(save(f,null,0,{bindings:{...f.bindings,periodBindings:{}}})).rejects.toThrow(/period/);await expect(db.query('select save_generation_profile($1,$2,$3,1,$4,$5,null,0)',[f.section,f.template,f.mapping.id,hash,{...f.bindings,lrn:'123456789012'}])).rejects.toThrow(/bindings/);const profile=await save(f);const s=await snapshot(f);expect(()=>validateBindings({periodBindings:{},subjectBindings:{}},f.def,s.periods,s.subjects)).toThrow();await db.query("update section_subjects set status='inactive' where id=$1",[f.subject]);expect(()=>verifyProfile({...s,subjects:[]})).toThrow(/subject/);await expect(save(f,profile.id,1)).rejects.toThrow(/subject/);});});
it('archives block snapshots and generation; profile contains configuration only, grades remain unchanged',async()=>{const f=await fixture();await actor(f.teacher,async()=>{const before=(await db.query('select * from section_grade_entries where section_id=$1',[f.section])).rows;await save(f);const s=await snapshot(f);expect(Object.keys(s.profile!).sort()).toEqual(['id','teacher_id','section_id','template_id','mapping_id','mapping_revision','template_sha256','bindings','revision','created_at','updated_at'].sort());valuesForLearner(s,f.def,s.learners[0]);expect((await db.query('select * from section_grade_entries where section_id=$1',[f.section])).rows).toEqual(before);await db.query("update sections set status='archived' where id=$1",[f.section]);expect(await snapshot(f)).toBeNull();expect(()=>verifyProfile({...s,section:{...s.section,status:'archived'}})).toThrow(/active/);});});
