import {chooseOption} from './helpers/custom-select';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
const mock=vi.hoisted(()=>({load:vi.fn(),save:vi.fn(),review:vi.fn(),setup:vi.fn(),saveSetup:vi.fn()}));
vi.mock('@/features/report-card-generation/actions',()=>({loadCompatibility:mock.load,saveCompatibility:mock.save,reviewReadiness:mock.review}));
vi.mock('@/features/gradebook/actions',()=>({loadGradebookSetup:mock.setup,saveGradebookSetup:mock.saveSetup}));
vi.mock('next/navigation',()=>({useRouter:()=>({refresh:vi.fn()})}));
import {GenerationWorkspace} from '@/features/report-card-generation/workspace';
afterEach(cleanup);beforeEach(()=>{vi.resetAllMocks();HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};});
const config={definition:{periods:[{key:'period_1',label:'Term 1'}],subjects:[{key:'subject-key',label:'Math'}]},mappingId:'mapping',mappingRevision:1,sha:'a'.repeat(64),profile:null,periods:[{id:'period-id',key:'period_1',label:'Term 1'}],subjects:[{id:'subject-id',name:'Math',position:1}]};
function renderWorkspace(){render(<GenerationWorkspace sectionId="section" templates={[{id:'template',name:'Reviewed template'}]}/>);chooseOption(screen.getByRole('combobox',{name:'Active template with a reviewed mapping'}),'template');}
it('does not silently match identical labels and requires confirmation before saving',async()=>{mock.load.mockResolvedValue({ok:true,data:config});renderWorkspace();fireEvent.click(screen.getByRole('button',{name:'Configure compatibility'}));const period=await screen.findByRole('combobox',{name:'Template Term 1 → Section period'}),subject=screen.getByRole('combobox',{name:'Template Math → Section subject'});expect(period).toHaveTextContent('Choose Section period');expect(subject).toHaveTextContent('Choose Section subject');expect(screen.getByRole('button',{name:'Save compatibility'})).toBeDisabled();expect(mock.save).not.toHaveBeenCalled();chooseOption(period,'period-id');chooseOption(subject,'subject-id');fireEvent.click(screen.getByLabelText('I confirm these period and subject bindings.'));mock.save.mockImplementation(async input=>({ok:true,data:{id:'profile',revision:1,bindings:input.bindings}}));fireEvent.click(screen.getByRole('button',{name:'Save compatibility'}));await waitFor(()=>expect(mock.save).toHaveBeenCalledOnce());expect(mock.save.mock.calls[0][0].bindings).toEqual({periodBindings:{period_1:'period-id'},subjectBindings:{'subject-key':'subject-id'}});expect(screen.getByRole('button',{name:'Review readiness'})).toBeEnabled();});
it('shows loading feedback and prevents repeat requests while configuring',async()=>{let resolve!:(value:unknown)=>void;mock.load.mockReturnValue(new Promise(r=>{resolve=r;}));renderWorkspace();const button=screen.getByRole('button',{name:'Configure compatibility'});fireEvent.click(button);fireEvent.click(button);expect(mock.load).toHaveBeenCalledOnce();expect(button).toBeDisabled();expect(screen.getByRole('status')).toHaveTextContent('Loading compatibility');resolve({ok:false,error:'Please retry'});expect(await screen.findByRole('alert')).toHaveTextContent('Please retry');});
it('shows zero and missing values and requires both grade review and formula confirmation',async()=>{const bindings={periodBindings:{period_1:'period-id'},subjectBindings:{'subject-key':'subject-id'}};mock.load.mockResolvedValue({ok:true,data:{...config,profile:{id:'profile',revision:1,bindings}}});mock.review.mockResolvedValue({ok:true,data:{digest:'a'.repeat(64),profileId:'profile',profileRevision:1,learnerId:'learner',learners:[{id:'learner',display_name:'Ana',missingCount:1,warnings:['LRN missing']}],missing:1,complete:0,periodCount:1,subjectCount:1,formulaTargets:['Front!A1'],values:[{id:'grade',label:'Grade',location:{sheet:'Front',address:'A1'},value:0},{id:'lrn',label:'LRN',location:{sheet:'Front',address:'A2'},value:null}]}});renderWorkspace();fireEvent.click(screen.getByRole('button',{name:'Configure compatibility'}));await screen.findByRole('button',{name:'Review readiness'});fireEvent.click(screen.getByRole('button',{name:'Review readiness'}));expect((await screen.findAllByText('Missing',{exact:true}))[0]).toBeVisible();expect(screen.getByRole('cell',{name:'0'})).toBeVisible();const generate=screen.getByRole('button',{name:'Generate one'});expect(generate).toBeDisabled();fireEvent.click(screen.getByLabelText('I reviewed the Section Grade Book and accept the missing values shown.'));expect(generate).toBeDisabled();fireEvent.click(screen.getByLabelText('I confirm replacing these mapped formulas.'));expect(generate).toBeEnabled();chooseOption(screen.getByRole('combobox',{name:'Template Term 1 → Section period'}),'');expect(screen.queryByRole('button',{name:'Generate one'})).toBeNull();});

it('adds a saved class subject to an empty Section and reloads compatibility after saving',async()=>{
  mock.load.mockResolvedValueOnce({ok:true,data:{...config,subjects:[]}}).mockResolvedValueOnce({ok:true,data:{...config,subjects:[{id:'calculus-id',name:'Calculus',position:1}]}});
  mock.setup.mockResolvedValue({ok:true,data:{book:{section:{id:'section'},periods:[{id:'period-id',key:'period_1',label:'Term 1',position:1,status:'active',updated_at:'stamp'}],subjects:[],entries:[],classes:[],learners:[]},subjectOptions:['Calculus']}});
  mock.saveSetup.mockResolvedValue({ok:true});renderWorkspace();fireEvent.click(screen.getByRole('button',{name:'Configure compatibility'}));
  expect(await screen.findByText(/This Section has no Grade Book subjects/)).toBeVisible();expect(screen.getByRole('combobox',{name:/Template Math.*Section subject/})).toBeDisabled();
  fireEvent.click(screen.getByRole('button',{name:'Add or manage Section subjects'}));await screen.findByRole('heading',{name:'Manage Grade Book'});
  fireEvent.click(screen.getByRole('button',{name:'Add subject manually'}));chooseOption(screen.getByRole('combobox',{name:'Subject name'}),'Calculus');
  fireEvent.click(screen.getByRole('button',{name:'Save setup'}));fireEvent.click(screen.getAllByRole('button',{name:'Save setup'}).at(-1)!);
  await waitFor(()=>expect(mock.saveSetup).toHaveBeenCalledOnce());expect(mock.saveSetup.mock.calls[0][0].subjects[0].name).toBe('Calculus');
  await waitFor(()=>expect(mock.load).toHaveBeenCalledTimes(2));chooseOption(screen.getByRole('combobox',{name:/Template Math.*Section subject/}),'calculus-id');expect(mock.save).not.toHaveBeenCalled();
});
