// @vitest-environment node
import {beforeAll,afterAll,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import type {PGlite} from '@electric-sql/pglite';
import {database,migrate} from './helpers/database';
import {mappingDefinition} from './helpers/mapping-fixture';
let db:PGlite;const hash='a'.repeat(64),sheet={name:'Front page',index:0,state:'visible',rowExtent:30,columnExtent:9,mergeCount:1,formulaCount:0,hasImages:false,hasExternalReferences:false,hasPrintArea:false,hasFreezePane:false,truncated:false},metadata={formatVersion:1,sheets:[sheet]};
beforeAll(async()=>{db=await database();},30000);afterAll(async()=>{await db?.close();});
async function owner(){const id=randomUUID();await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,'mapping@example.com',now())",[id]);await db.query("update profiles set access_status='active' where id=$1",[id]);return id;}
async function fixture(){const teacher=await owner(),id=randomUUID();await db.query("insert into report_card_templates(id,teacher_id,name,original_filename,storage_path,mime_type,file_size_bytes,file_sha256,sheet_count,workbook_metadata) values($1,$2,'Mapping','blank.xlsx',$3,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',100,$4,1,$5)",[id,teacher,`${teacher}/${id}/source.xlsx`,hash,metadata]);return {teacher,id};}
async function actor(id:string,fn:()=>Promise<void>,role='authenticated'){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${role}`);try{await fn();}finally{await db.exec('reset role');}}
type Saved={id:string;revision:number;mapping_definition:unknown};
async function save(id:string,def:unknown=mappingDefinition(hash),expected:string|null=null,revision=0){return (await db.query<{saved:Saved}>("select to_jsonb(save_report_card_mapping($1,$2::jsonb,$3,$4,'reviewed')) saved",[id,JSON.stringify(def),expected,revision])).rows[0].saved;}
it('creates one mapping, edits by revision and resets without touching source',async()=>{const f=await fixture(),source=(await db.query('select * from report_card_templates where id=$1',[f.id])).rows;await actor(f.teacher,async()=>{const first=await save(f.id);expect(first.revision).toBe(1);const changed=mappingDefinition(hash,4),second=await save(f.id,changed,first.id,1);expect(second.id).toBe(first.id);expect(second.revision).toBe(2);await expect(save(f.id,changed,first.id,1)).rejects.toMatchObject({code:'PT409'});await expect(db.query('select reset_report_card_mapping($1,$2,1)',[f.id,first.id])).rejects.toMatchObject({code:'PT409'});await db.query('select reset_report_card_mapping($1,$2,2)',[f.id,first.id]);expect((await db.query('select * from report_card_template_mappings')).rows).toHaveLength(0);const recreated=await save(f.id);expect(recreated.id).not.toBe(first.id);await expect(save(f.id,changed,first.id,1)).rejects.toMatchObject({code:'PT409'});});expect((await db.query('select * from report_card_templates where id=$1',[f.id])).rows).toEqual(source);});
it.each(['other','admin','pending','suspended','unverified','anon'])('denies %s read/save/reset',async state=>{const f=await fixture();let saved:Saved;await actor(f.teacher,async()=>{saved=await save(f.id);});let who=f.teacher;if(state==='pending'||state==='suspended')await db.query('update profiles set access_status=$1 where id=$2',[state,who]);if(state==='unverified')await db.query('update auth.users set email_confirmed_at=null where id=$1',[who]);if(state==='other'||state==='admin'){who=await owner();if(state==='admin')await db.query("update profiles set role='admin' where id=$1",[who]);}await actor(who,async()=>{const read=db.query('select * from report_card_template_mappings where template_id=$1',[f.id]);if(state==='anon')await expect(read).rejects.toThrow(/permission/);else expect((await read).rows).toHaveLength(0);await expect(save(f.id)).rejects.toThrow();await expect(db.query('select reset_report_card_mapping($1,$2,1)',[f.id,saved!.id])).rejects.toThrow();},state==='anon'?'anon':'authenticated');});
it('requires RPC mutations and prevents hash/owner spoofing even privileged mistakes',async()=>{const f=await fixture();await actor(f.teacher,async()=>{await expect(db.query("insert into report_card_template_mappings(teacher_id,template_id,mapping_definition,revision,status) values($1,$2,$3,1,'draft')",[f.teacher,f.id,mappingDefinition(hash)])).rejects.toThrow(/permission/);await expect(save(f.id,mappingDefinition('b'.repeat(64)))).rejects.toThrow(/SHA/);});await expect(db.query("insert into report_card_template_mappings(teacher_id,template_id,mapping_definition,revision,status) values($1,$2,$3,1,'draft')",[await owner(),f.id,mappingDefinition(hash)])).rejects.toThrow(/owner/);});
it.each(['A0','J1','A31','C8:F8'])('rejects invalid bounds or conflicting target %s',async address=>{const f=await fixture(),def=mappingDefinition(hash);def.fields.section_name={sheet:'Front page',address};await actor(f.teacher,async()=>{await expect(save(f.id,def)).rejects.toThrow();});});
it('rejects missing sheet, period/subject duplicates, undefined outputs and actual LRN values',async()=>{const f=await fixture();await actor(f.teacher,async()=>{const d=mappingDefinition(hash);d.fields.lrn={sheet:'Missing',address:'A1'};await expect(save(f.id,d)).rejects.toThrow();delete d.fields.lrn;await expect(save(f.id,{...d,lrn:'123456789012'})).rejects.toThrow();await expect(save(f.id,{...d,fields:{lrn:{sheet:'Front page',address:'A1',value:'123456789012'}}})).rejects.toThrow();await expect(save(f.id,{...d,periods:[d.periods[0],d.periods[0]]})).rejects.toThrow();await expect(save(f.id,{...d,subjects:[d.subjects[0],d.subjects[0]]})).rejects.toThrow();d.subjects[0].outputs.period_8={sheet:'Front page',address:'I25'};await expect(save(f.id,d)).rejects.toThrow();});});
it('archives mappings read-only and cascades template deletion',async()=>{const f=await fixture();await actor(f.teacher,async()=>{const saved=await save(f.id);await db.query("update report_card_templates set status='archived' where id=$1",[f.id]);expect((await db.query('select * from report_card_template_mappings where template_id=$1',[f.id])).rows).toHaveLength(1);await expect(save(f.id,mappingDefinition(hash),saved.id,1)).rejects.toThrow(/Reactivate/);await db.query('delete from report_card_templates where id=$1',[f.id]);expect((await db.query('select * from report_card_template_mappings where template_id=$1',[f.id])).rows).toHaveLength(0);});});
it('upgrades populated 0018 without changing templates or existing public rows',async()=>{const old=await database(18);try{const teacher=randomUUID(),id=randomUUID();await old.query("insert into auth.users(id,email,email_confirmed_at) values($1,'upgrade@example.com',now())",[teacher]);await old.query("insert into report_card_templates(id,teacher_id,name,original_filename,storage_path,mime_type,file_size_bytes,file_sha256,sheet_count,workbook_metadata) values($1,$2,'Blank','blank.xlsx',$3,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',100,$4,1,$5)",[id,teacher,`${teacher}/${id}/source.xlsx`,hash,metadata]);const tables=(await old.query<{tablename:string}>("select tablename from pg_tables where schemaname='public' order by tablename")).rows;const snapshot=()=>Promise.all(tables.map(t=>old.query(`select to_jsonb(t) row from public.${t.tablename} t order by to_jsonb(t)::text`)));const before=await snapshot();await migrate(old,19,19);expect(await snapshot()).toEqual(before);}finally{await old.close();}},30000);
