// @vitest-environment node
import {beforeEach,it,expect,vi} from 'vitest';
import {randomUUID,createHash} from 'node:crypto';
const mock=vi.hoisted(()=>({access:vi.fn(),owned:vi.fn(),bytes:vi.fn(),rpc:vi.fn()}));
vi.mock('server-only',()=>({}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
vi.mock('@/features/report-card-templates/data',()=>({templateAccess:mock.access,ownedTemplate:mock.owned,originalBytes:mock.bytes,TemplateError:class extends Error{}}));
import {reviewMapping,saveMapping,resetMapping} from '@/features/report-card-mappings/actions';
import {mappingWorkbook,mappingDefinition} from './helpers/mapping-fixture';
let input:ReturnType<typeof makeInput>,bytes:Buffer;
function makeInput(hash:string){return {templateId:randomUUID(),expectedId:null,revision:0,definition:mappingDefinition(hash),status:'reviewed'};}
beforeEach(async()=>{vi.resetAllMocks();bytes=await mappingWorkbook();input=makeInput(createHash('sha256').update(bytes).digest('hex'));mock.access.mockResolvedValue({user:{id:randomUUID()},supabase:{rpc:mock.rpc}});mock.owned.mockResolvedValue({id:input.templateId,status:'active',file_sha256:input.definition.templateSha256});mock.bytes.mockResolvedValue(bytes);mock.rpc.mockResolvedValue({data:{id:randomUUID(),revision:1,mapping_definition:input.definition,status:'reviewed'}});});
it('review is read-only and save validates source then writes only the mapping RPC',async()=>{const hash=createHash('sha256').update(bytes).digest('hex');input.definition.fields.learner_name!.address='D8';const review=await reviewMapping(input);expect(review.ok&&review.data.definition.fields.learner_name?.address).toBe('C8:F8');expect(mock.rpc).not.toHaveBeenCalled();expect(await saveMapping({...input,teacher_id:randomUUID(),grade:99,lrn:'123456789012'})).toMatchObject({ok:true});expect(mock.rpc).toHaveBeenCalledWith('save_report_card_mapping',{p_template:input.templateId,p_expected_id:null,p_revision:0,p_status:'reviewed',p_definition:expect.objectContaining({fields:{learner_name:{sheet:'Front page',address:'C8:F8'}}})});expect(JSON.stringify(mock.rpc.mock.calls[0][1])).not.toContain('123456789012');expect(createHash('sha256').update(bytes).digest('hex')).toBe(hash);});
it('rejects source hash mismatch and conflicting outputs before writes',async()=>{input.definition.templateSha256='f'.repeat(64);expect(await saveMapping(input)).toMatchObject({ok:false,error:expect.stringContaining('different source')});expect(mock.rpc).not.toHaveBeenCalled();input.definition.templateSha256=createHash('sha256').update(bytes).digest('hex');input.definition.fields.section_name={sheet:'Front page',address:'D8'};expect(await saveMapping(input)).toMatchObject({ok:false,error:expect.stringContaining('overlaps')});expect(mock.rpc).not.toHaveBeenCalled();});
it('preserves edits on stale revision response and never retries an overwrite automatically',async()=>{mock.rpc.mockResolvedValue({error:{code:'PT409'}});expect(await saveMapping(input)).toMatchObject({ok:false,error:expect.stringContaining('another session')});expect(mock.rpc).toHaveBeenCalledOnce();});
it.each(['access','owned','bytes'] as const)('denies writes when %s verification fails',async gate=>{mock[gate].mockRejectedValue(new Error('Denied'));expect(await saveMapping(input)).toMatchObject({ok:false});expect(mock.rpc).not.toHaveBeenCalled();});
it('archived source stays read-only',async()=>{mock.owned.mockResolvedValue({status:'archived'});expect(await saveMapping(input)).toMatchObject({ok:false,error:expect.stringContaining('Reactivate')});expect(mock.bytes).not.toHaveBeenCalled();expect(mock.rpc).not.toHaveBeenCalled();});
it('reset requires explicit confirmation and exact identity/revision',async()=>{expect(await resetMapping(input)).toMatchObject({ok:false});expect(mock.rpc).not.toHaveBeenCalled();expect(await resetMapping({...input,confirmed:true})).toMatchObject({ok:true});expect(mock.rpc).toHaveBeenCalledWith('reset_report_card_mapping',{p_template:input.templateId,p_expected_id:null,p_revision:0});expect(mock.bytes).not.toHaveBeenCalled();});
it('rejects cell contents/unknown properties inside the saved definition',async()=>{expect(await saveMapping({...input,definition:{...input.definition,fields:{lrn:{sheet:'Front page',address:'A1',value:'123456789012'}}}})).toMatchObject({ok:false});expect(mock.rpc).not.toHaveBeenCalled();});
