// @vitest-environment node
import {it,expect,vi} from 'vitest';
import {randomUUID} from 'node:crypto';
vi.mock('server-only',()=>({}));
import {temporaryDownload,removeTemporary} from '@/features/report-card-generation/temporary-output';
import type {TemplateContext} from '@/features/report-card-templates/data';
import {TemplateError} from '@/features/report-card-templates/data';
function fixture(){const upload=vi.fn().mockResolvedValue({}),remove=vi.fn().mockResolvedValue({}),sign=vi.fn().mockResolvedValue({data:{signedUrl:'https://fixture/signed'}}),context={user:{id:randomUUID()},supabase:{storage:{from:()=>({upload,remove,createSignedUrl:sign})}}} as unknown as TemplateContext;return {context,upload,remove,sign};}
it('uses private no-store random paths, 60-second signing and repeated freshness checks',async()=>{const f=fixture(),check=vi.fn(),r=await temporaryDownload(f.context,Buffer.from('synthetic output'),'application/zip',check);expect(f.upload.mock.calls[0][0]).toMatch(new RegExp(`^\\d{13}/${f.context.user.id}/[a-f0-9-]{36}\\.zip$`));expect(f.upload.mock.calls[0][2]).toMatchObject({upsert:false,headers:{'cache-control':'private, no-store, max-age=0'}});expect(f.sign).toHaveBeenCalledWith(r.cleanupToken,60);expect(check).toHaveBeenCalledTimes(2);await removeTemporary(f.context,r.cleanupToken);await removeTemporary(f.context,r.cleanupToken);expect(f.remove).toHaveBeenCalledTimes(2);await expect(removeTemporary(f.context,`${Date.now()}/${randomUUID()}/${randomUUID()}.xlsx`)).rejects.toThrow();});
it('cleans output on lost upload responses and signing or stale-data failures without exposing internals',async()=>{for(const phase of ['upload','sign','stale']){const f=fixture(),check=vi.fn();if(phase==='upload')f.upload.mockResolvedValue({error:{message:'internal'}});if(phase==='sign')f.sign.mockResolvedValue({error:{message:'internal'}});if(phase==='stale')check.mockRejectedValue(new TemplateError('Review again',409));await expect(temporaryDownload(f.context,Buffer.from('synthetic'),'application/zip',check)).rejects.toThrow(phase==='stale'?'Review again':'A temporary download failed. Try generating again.');expect(f.remove).toHaveBeenCalledOnce();}});
