import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
const mock = vi.hoisted(() => ({ path: '/sections', create: vi.fn(), push: vi.fn(), refresh: vi.fn() }));
vi.mock('next/navigation', () => ({ usePathname: () => mock.path, useRouter: () => ({ push: mock.push, refresh: mock.refresh }) }));
vi.mock('next/link', () => ({ default: ({ children, ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) => <a {...props}>{children}</a>, useLinkStatus: () => ({ pending: false }) }));
vi.mock('next/image', () => ({ default: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <span aria-label={props.alt} /> }));
vi.mock('@/components/layout/account-menu', () => ({ AccountMenu: () => <div>Account</div> }));
vi.mock('@/features/sections/actions', () => ({ createSection: mock.create, updateSection: vi.fn() }));
import { AppShell } from '@/components/layout/app-shell';
import { ClassAreaTabs } from '@/features/sections/area-tabs';
import { SectionForm } from '@/features/sections/section-form';
beforeEach(() => { vi.clearAllMocks(); mock.path = '/sections'; });
afterEach(cleanup);
it.each(['/sections', '/sections/new', '/sections/one/learners'])('keeps Classes selected with exactly five mobile destinations on %s', path => {
  mock.path = path; render(<AppShell><ClassAreaTabs /></AppShell>);
  const nav = within(screen.getByRole('navigation', { name: 'Mobile navigation' }));
  expect(nav.getAllByRole('link')).toHaveLength(5);
  expect(nav.getByRole('link', { name: 'Classes' })).toHaveAttribute('aria-current', 'page');
  expect(within(screen.getByRole('navigation', { name: 'Classes and Sections' })).getByRole('link', { name: 'Sections' })).toHaveAttribute('aria-current', 'page');
});
it('locks Section creation, shows progress and uses the same request ID after a retry', async () => {
  let complete: (result: unknown) => void = () => {};
  mock.create.mockImplementation(() => new Promise(resolve => { complete = resolve; }));
  render(<SectionForm />);
  fireEvent.change(screen.getByLabelText('Section name'), { target: { value: 'Rizal' } });
  fireEvent.change(screen.getByLabelText('Grade level'), { target: { value: 'Grade 8' } });
  fireEvent.change(screen.getByLabelText('School year'), { target: { value: '2026-2027' } });
  fireEvent.click(screen.getByLabelText('I am the adviser of this Section'));
  const form = screen.getByRole('button', { name: 'Create Section' }).closest('form')!;
  fireEvent.submit(form); fireEvent.submit(form);
  expect(mock.create).toHaveBeenCalledTimes(1);
  expect(screen.getByRole('button', { name: 'Saving Section…' })).toBeDisabled();
  complete({ ok: false, error: 'Try again.' });
  await screen.findByRole('alert');
  fireEvent.submit(form);
  expect(mock.create).toHaveBeenCalledTimes(2);
  expect(mock.create.mock.calls[1][0].requestId).toBe(mock.create.mock.calls[0][0].requestId);
  expect(mock.create.mock.calls[1][0]).toMatchObject({ is_adviser: true });
  complete({ ok: true, id: 'section' });
  await waitFor(() => expect(mock.push).toHaveBeenCalledWith('/sections/section'));
});
